/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import static GUI.FrameGestionProduitAdmin.prod_id;
import com.restfb.DefaultFacebookClient;
import com.restfb.FacebookClient;
import com.restfb.Parameter;
import com.restfb.types.FacebookType;
import com.restfb.types.Page;
import com.restfb.types.User;
import dao.ProduitDao;
import dao.ZoneDao;
import entite.Produit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.TableModel;
import utils.ProduitClientModel;
import utils.ProduitModel;
import java.awt.Color;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import utils.PostFile;
import utils.ProduitByCategorieModel;

/**
 *
 * @author Lilya Thebti
 */
public class AllForDealFrame extends javax.swing.JFrame {

    /**
     * Creates new form AllForDealFrame
     */
    
    // partie Lilya
    static Connection con;
    static ResultSet res;
    static PreparedStatement ps;
    static Statement stm;
     ResultSet rs = null;
    ResultSet rsId = null;   
    private static String categorie;
    String im;

   public static String getCategorie() {
        return categorie;
    }
    ProduitDao pdao = new ProduitDao();
    ZoneDao zdao = new ZoneDao();
    
    //fin Partie Lilya
    public AllForDealFrame() {
        initComponents();
        
        btnProduits.setOpaque(false);
        btnProduits.setContentAreaFilled(false);
        btnProduits.setBorderPainted(false);

        btnAccueil.setOpaque(false);
        btnAccueil.setContentAreaFilled(false);
        btnAccueil.setBorderPainted(false);
        
        btnPanier.setOpaque(false);
        btnPanier.setContentAreaFilled(false);
        btnPanier.setBorderPainted(false);
        
        btnMessage.setOpaque(false);
        btnMessage.setContentAreaFilled(false);
        btnMessage.setBorderPainted(false);
        
        btnNotif.setOpaque(false);
        btnNotif.setContentAreaFilled(false);
        btnNotif.setBorderPainted(false);
        
        btnServices.setOpaque(false);
        btnServices.setContentAreaFilled(false);
        btnServices.setBorderPainted(false);
        
        btnReclam.setOpaque(false);
        btnReclam.setContentAreaFilled(false);
        btnReclam.setBorderPainted(false);
        
        btnProfile.setOpaque(false);
        btnProfile.setContentAreaFilled(false);
        btnProfile.setBorderPainted(false);
        
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuPanel = new javax.swing.JPanel();
        btnPanier = new javax.swing.JButton();
        btnProfile = new javax.swing.JButton();
        btnReclam = new javax.swing.JButton();
        btnMessage = new javax.swing.JButton();
        btnNotif = new javax.swing.JButton();
        btnServices = new javax.swing.JButton();
        btnProduits = new javax.swing.JButton();
        btnAccueil = new javax.swing.JButton();
        ParentPanel = new javax.swing.JPanel();
        AccueilPanel = new javax.swing.JPanel();
        ProduitPanel = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbProduits = new javax.swing.JTable();
        btnPartager = new javax.swing.JButton();
        AjoutPanier = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        cbCategorieR = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        btnRechercher = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbRecherche = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnAjouter = new javax.swing.JButton();
        tfNomP = new javax.swing.JTextField();
        tfPrix = new javax.swing.JTextField();
        cbCategorie = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        LAlerte = new javax.swing.JTextField();
        tfReduction = new javax.swing.JTextField();
        tfQuantite = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfPointBonus = new javax.swing.JTextField();
        cbZone = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taDescription = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        tfTVA = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        tfPhoto = new javax.swing.JTextField();
        btnParcourir = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMesProduits = new javax.swing.JTable();
        tfNomP1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cbCategorie1 = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        tfPrix1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cbZone1 = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        tfTVA1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        tfReduction1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        tfQuantite1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        tfPointBonus1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        taDescription1 = new javax.swing.JTextArea();
        labelId = new javax.swing.JLabel();
        bntConsulter = new javax.swing.JButton();
        btnSupprimer = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        p2 = new javax.swing.JPanel();
        limage1 = new javax.swing.JLabel();
        lcat1 = new javax.swing.JLabel();
        lquantite1 = new javax.swing.JLabel();
        lprix1 = new javax.swing.JLabel();
        lbonus1 = new javax.swing.JLabel();
        lnom1 = new javax.swing.JLabel();
        p4 = new javax.swing.JPanel();
        limage2 = new javax.swing.JLabel();
        lcat2 = new javax.swing.JLabel();
        lquantite2 = new javax.swing.JLabel();
        lprix2 = new javax.swing.JLabel();
        lbonus2 = new javax.swing.JLabel();
        lnom2 = new javax.swing.JLabel();
        p5 = new javax.swing.JPanel();
        limage3 = new javax.swing.JLabel();
        lcat3 = new javax.swing.JLabel();
        lquantite3 = new javax.swing.JLabel();
        lprix3 = new javax.swing.JLabel();
        lbonus3 = new javax.swing.JLabel();
        lnom3 = new javax.swing.JLabel();
        p3 = new javax.swing.JPanel();
        lcat4 = new javax.swing.JLabel();
        lnom4 = new javax.swing.JLabel();
        limage4 = new javax.swing.JLabel();
        lbonus4 = new javax.swing.JLabel();
        lquantite4 = new javax.swing.JLabel();
        lprix4 = new javax.swing.JLabel();
        p6 = new javax.swing.JPanel();
        lcat5 = new javax.swing.JLabel();
        lnom5 = new javax.swing.JLabel();
        limage5 = new javax.swing.JLabel();
        lbonus5 = new javax.swing.JLabel();
        lquantite5 = new javax.swing.JLabel();
        lprix5 = new javax.swing.JLabel();
        p1 = new javax.swing.JPanel();
        lnom = new javax.swing.JLabel();
        lprix = new javax.swing.JLabel();
        lquantite = new javax.swing.JLabel();
        lbonus = new javax.swing.JLabel();
        lcat = new javax.swing.JLabel();
        limage = new javax.swing.JLabel();
        AjouterProduitPanier = new javax.swing.JButton();
        PanelService = new javax.swing.JPanel();
        PanierReclamation = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnPanier.setText("jButton2");
        btnPanier.setPreferredSize(new java.awt.Dimension(50, 40));

        btnProfile.setPreferredSize(new java.awt.Dimension(50, 40));

        btnReclam.setText("jButton2");
        btnReclam.setOpaque(false);
        btnReclam.setPreferredSize(new java.awt.Dimension(50, 40));

        btnMessage.setPreferredSize(new java.awt.Dimension(50, 40));

        btnNotif.setPreferredSize(new java.awt.Dimension(50, 40));

        btnServices.setText("jButton2");
        btnServices.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        btnServices.setOpaque(false);
        btnServices.setPreferredSize(new java.awt.Dimension(50, 40));

        btnProduits.setText("jButton2");
        btnProduits.setBorder(null);
        btnProduits.setPreferredSize(new java.awt.Dimension(50, 40));
        btnProduits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProduitsActionPerformed(evt);
            }
        });

        btnAccueil.setPreferredSize(new java.awt.Dimension(50, 40));
        btnAccueil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccueilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuPanelLayout = new javax.swing.GroupLayout(MenuPanel);
        MenuPanel.setLayout(MenuPanelLayout);
        MenuPanelLayout.setHorizontalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPanier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNotif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9))
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAccueil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProduits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnServices, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnReclam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MenuPanelLayout.setVerticalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPanier, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNotif, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReclam, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnServices, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProduits, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAccueil, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        ParentPanel.setLayout(new java.awt.CardLayout());

        AccueilPanel.setLayout(null);
        ParentPanel.add(AccueilPanel, "card3");

        ProduitPanel.setPreferredSize(new java.awt.Dimension(790, 399));

        jTabbedPane1.setPreferredSize(new java.awt.Dimension(790, 480));
        jTabbedPane1.setSize(790,480);

        jScrollPane3.setSize(500, 600);

        tbProduits.setSize(600, 600);
        tbProduits.setModel(new ProduitModel());
        tbProduits.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbProduitsMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbProduits);

        btnPartager.setText("Partager");
        btnPartager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPartagerActionPerformed(evt);
            }
        });

        AjoutPanier.setText("Ajouter Au panier");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(btnPartager)
                        .addGap(49, 49, 49)
                        .addComponent(AjoutPanier))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(244, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(142, 142, 142)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPartager)
                    .addComponent(AjoutPanier))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Offres", jPanel2);

        jPanel4.setSize(790,540);

        jLabel10.setText("Choisisser une catégorie:");

        btnRechercher.setText("Rechercher");
        btnRechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRechercherActionPerformed(evt);
            }
        });

        tbRecherche.setModel(new ProduitByCategorieModel());
        jScrollPane5.setViewportView(tbRecherche);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel10)
                        .addGap(60, 60, 60)
                        .addComponent(cbCategorieR, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87)
                        .addComponent(btnRechercher))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 696, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCategorieR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(btnRechercher))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(249, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Rechercher un produit", jPanel4);

        jPanel1.setLayout(null);

        jLabel1.setText("Nom Produit");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(70, 60, 58, 14);

        jLabel2.setText("Catégorie");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(70, 110, 47, 14);

        jLabel3.setText("Prix");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(100, 150, 18, 14);

        jLabel4.setText("Gouvernorat");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(60, 192, 61, 14);

        jLabel5.setText("Réduction");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(73, 270, 48, 14);

        btnAjouter.setText("Ajouter");
        btnAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterActionPerformed(evt);
            }
        });
        jPanel1.add(btnAjouter);
        btnAjouter.setBounds(680, 400, 69, 23);

        tfNomP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomPActionPerformed(evt);
            }
        });
        jPanel1.add(tfNomP);
        tfNomP.setBounds(169, 61, 80, 25);
        jPanel1.add(tfPrix);
        tfPrix.setBounds(170, 150, 80, 20);

        cbCategorie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCategorieActionPerformed(evt);
            }
        });
        jPanel1.add(cbCategorie);
        cbCategorie.setBounds(170, 110, 80, 20);

        jLabel6.setText("Quantité");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(80, 310, 42, 14);

        LAlerte.setEditable(false);
        LAlerte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LAlerteActionPerformed(evt);
            }
        });
        jPanel1.add(LAlerte);
        LAlerte.setBounds(340, 250, 296, 40);
        jPanel1.add(tfReduction);
        tfReduction.setBounds(170, 270, 80, 20);
        jPanel1.add(tfQuantite);
        tfQuantite.setBounds(170, 310, 80, 20);

        jLabel7.setText("Points Bonus");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(60, 350, 61, 14);
        jPanel1.add(tfPointBonus);
        tfPointBonus.setBounds(170, 350, 80, 20);

        jPanel1.add(cbZone);
        cbZone.setBounds(170, 190, 80, 20);

        jLabel8.setText("Description");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(334, 66, 53, 14);

        taDescription.setColumns(20);
        taDescription.setRows(5);
        jScrollPane1.setViewportView(taDescription);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(340, 100, 166, 96);

        jLabel9.setText("TVA");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(102, 242, 19, 14);
        jPanel1.add(tfTVA);
        tfTVA.setBounds(170, 240, 80, 20);

        jLabel20.setText("Photos");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(80, 400, 33, 14);
        jPanel1.add(tfPhoto);
        tfPhoto.setBounds(170, 400, 140, 20);

        btnParcourir.setText("Parcourir");
        btnParcourir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParcourirActionPerformed(evt);
            }
        });
        jPanel1.add(btnParcourir);
        btnParcourir.setBounds(330, 400, 80, 23);

        jTabbedPane1.addTab("Ajouter Produit", jPanel1);

        jPanel3.setLayout(null);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel5);
        jPanel5.setBounds(1072, 430, 0, 0);

        tblMesProduits.setBackground(Color.BLUE);
        tblMesProduits.setModel(new ProduitClientModel());
        tblMesProduits.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMesProduitsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblMesProduits);

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(310, 10, 470, 413);

        tfNomP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomP1ActionPerformed(evt);
            }
        });
        jPanel3.add(tfNomP1);
        tfNomP1.setBounds(128, 32, 80, 25);

        jLabel11.setText("Catégorie");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(10, 78, 47, 14);

        jPanel3.add(cbCategorie1);
        cbCategorie1.setBounds(128, 75, 80, 20);

        jLabel12.setText("Prix");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(39, 119, 18, 14);
        jPanel3.add(tfPrix1);
        tfPrix1.setBounds(128, 116, 80, 20);

        jLabel13.setText("Gouvernorat");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(10, 163, 61, 14);

        jPanel3.add(cbZone1);
        cbZone1.setBounds(128, 160, 80, 20);

        jLabel14.setText("TVA");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(52, 210, 19, 14);
        jPanel3.add(tfTVA1);
        tfTVA1.setBounds(128, 207, 80, 20);

        jLabel15.setText("Réduction");
        jPanel3.add(jLabel15);
        jLabel15.setBounds(23, 241, 48, 14);
        jPanel3.add(tfReduction1);
        tfReduction1.setBounds(128, 238, 80, 20);

        jLabel16.setText("Quantité");
        jPanel3.add(jLabel16);
        jLabel16.setBounds(29, 276, 42, 14);
        jPanel3.add(tfQuantite1);
        tfQuantite1.setBounds(128, 276, 80, 20);

        jLabel17.setText("Points Bonus");
        jPanel3.add(jLabel17);
        jLabel17.setBounds(10, 321, 61, 14);

        tfPointBonus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPointBonus1ActionPerformed(evt);
            }
        });
        jPanel3.add(tfPointBonus1);
        tfPointBonus1.setBounds(128, 332, 80, 20);

        jLabel18.setText("Description");
        jPanel3.add(jLabel18);
        jLabel18.setBounds(18, 370, 53, 14);

        taDescription1.setColumns(20);
        taDescription1.setRows(5);
        jScrollPane4.setViewportView(taDescription1);

        jPanel3.add(jScrollPane4);
        jScrollPane4.setBounds(128, 370, 166, 96);
        jPanel3.add(labelId);
        labelId.setBounds(130, 10, 70, 20);

        bntConsulter.setText("Consulter");
        bntConsulter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntConsulterActionPerformed(evt);
            }
        });
        jPanel3.add(bntConsulter);
        bntConsulter.setBounds(340, 450, 90, 23);

        btnSupprimer.setText("Supprimer");
        btnSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprimerActionPerformed(evt);
            }
        });
        jPanel3.add(btnSupprimer);
        btnSupprimer.setBounds(440, 450, 81, 23);

        jLabel19.setText("jLabel19");
        jPanel3.add(jLabel19);
        jLabel19.setBounds(330, 20, 560, 410);

        jTabbedPane1.addTab("Mes Produits", jPanel3);

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));

        limage1.setText("jLabel21");

        lcat1.setText("jLabel21");

        lquantite1.setText("jLabel23");

        lprix1.setText("jLabel22");

        lbonus1.setText("jLabel24");

        lnom1.setText("jLabel21");

        javax.swing.GroupLayout p2Layout = new javax.swing.GroupLayout(p2);
        p2.setLayout(p2Layout);
        p2Layout.setHorizontalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p2Layout.createSequentialGroup()
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(p2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lnom1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lprix1))
                    .addGroup(p2Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(lquantite1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lcat1)
                    .addComponent(lbonus1))
                .addGap(31, 31, 31))
            .addGroup(p2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(limage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        p2Layout.setVerticalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(limage1, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbonus1)
                    .addComponent(lprix1)
                    .addComponent(lnom1))
                .addGap(9, 9, 9)
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lcat1)
                    .addComponent(lquantite1))
                .addContainerGap())
        );

        limage2.setText("jLabel21");

        lcat2.setText("jLabel21");

        lquantite2.setText("jLabel23");

        lprix2.setText("jLabel22");

        lbonus2.setText("jLabel24");

        lnom2.setText("jLabel21");

        javax.swing.GroupLayout p4Layout = new javax.swing.GroupLayout(p4);
        p4.setLayout(p4Layout);
        p4Layout.setHorizontalGroup(
            p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p4Layout.createSequentialGroup()
                .addGroup(p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(p4Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lnom2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lprix2))
                    .addGroup(p4Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(lquantite2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lcat2)
                    .addComponent(lbonus2))
                .addGap(31, 31, 31))
            .addGroup(p4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(limage2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        p4Layout.setVerticalGroup(
            p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(limage2, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbonus2)
                    .addComponent(lprix2)
                    .addComponent(lnom2))
                .addGap(9, 9, 9)
                .addGroup(p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lcat2)
                    .addComponent(lquantite2))
                .addContainerGap())
        );

        limage3.setText("jLabel21");

        lcat3.setText("jLabel21");

        lquantite3.setText("jLabel23");

        lprix3.setText("jLabel22");

        lbonus3.setText("jLabel24");

        lnom3.setText("jLabel21");

        javax.swing.GroupLayout p5Layout = new javax.swing.GroupLayout(p5);
        p5.setLayout(p5Layout);
        p5Layout.setHorizontalGroup(
            p5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p5Layout.createSequentialGroup()
                .addGroup(p5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(p5Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lnom3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lprix3))
                    .addGroup(p5Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(lquantite3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(p5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lcat3)
                    .addComponent(lbonus3))
                .addGap(31, 31, 31))
            .addGroup(p5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(limage3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        p5Layout.setVerticalGroup(
            p5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(limage3, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(p5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbonus3)
                    .addComponent(lprix3)
                    .addComponent(lnom3))
                .addGap(9, 9, 9)
                .addGroup(p5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lcat3)
                    .addComponent(lquantite3))
                .addContainerGap())
        );

        lcat4.setText("jLabel21");

        lnom4.setText("jLabel21");

        limage4.setText("jLabel21");

        lbonus4.setText("jLabel24");

        lquantite4.setText("jLabel23");

        lprix4.setText("jLabel22");

        javax.swing.GroupLayout p3Layout = new javax.swing.GroupLayout(p3);
        p3.setLayout(p3Layout);
        p3Layout.setHorizontalGroup(
            p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p3Layout.createSequentialGroup()
                .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(p3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lnom4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lprix4))
                    .addGroup(p3Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(lquantite4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lcat4)
                    .addComponent(lbonus4))
                .addGap(31, 31, 31))
            .addGroup(p3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(limage4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        p3Layout.setVerticalGroup(
            p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(limage4, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbonus4)
                    .addComponent(lprix4)
                    .addComponent(lnom4))
                .addGap(9, 9, 9)
                .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lcat4)
                    .addComponent(lquantite4))
                .addContainerGap())
        );

        lcat5.setText("jLabel21");

        lnom5.setText("jLabel21");

        limage5.setText("jLabel21");

        lbonus5.setText("jLabel24");

        lquantite5.setText("jLabel23");

        lprix5.setText("jLabel22");

        javax.swing.GroupLayout p6Layout = new javax.swing.GroupLayout(p6);
        p6.setLayout(p6Layout);
        p6Layout.setHorizontalGroup(
            p6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p6Layout.createSequentialGroup()
                .addGroup(p6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(p6Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lnom5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lprix5))
                    .addGroup(p6Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(lquantite5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(p6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lcat5)
                    .addComponent(lbonus5))
                .addGap(31, 31, 31))
            .addGroup(p6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(limage5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        p6Layout.setVerticalGroup(
            p6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(limage5, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(p6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbonus5)
                    .addComponent(lprix5)
                    .addComponent(lnom5))
                .addGap(9, 9, 9)
                .addGroup(p6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lcat5)
                    .addComponent(lquantite5))
                .addContainerGap())
        );

        lnom.setText("jLabel21");

        lprix.setText("jLabel22");

        lquantite.setText("jLabel23");

        lbonus.setText("jLabel24");

        lcat.setText("jLabel21");

        limage.setText("jLabel21");

        javax.swing.GroupLayout p1Layout = new javax.swing.GroupLayout(p1);
        p1.setLayout(p1Layout);
        p1Layout.setHorizontalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p1Layout.createSequentialGroup()
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(p1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lnom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lprix))
                    .addGroup(p1Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(lquantite)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lcat)
                    .addComponent(lbonus))
                .addGap(31, 31, 31))
            .addGroup(p1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(limage, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        p1Layout.setVerticalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p1Layout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addComponent(limage, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbonus)
                    .addComponent(lprix)
                    .addComponent(lnom))
                .addGap(9, 9, 9)
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lcat)
                    .addComponent(lquantite))
                .addContainerGap())
        );

        AjouterProduitPanier.setText("Ajouter Au Panier");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(p4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(AjouterProduitPanier)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(p4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AjouterProduitPanier)
                        .addGap(29, 29, 29))))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("tab5", jPanel6);

        javax.swing.GroupLayout ProduitPanelLayout = new javax.swing.GroupLayout(ProduitPanel);
        ProduitPanel.setLayout(ProduitPanelLayout);
        ProduitPanelLayout.setHorizontalGroup(
            ProduitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProduitPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 799, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(294, Short.MAX_VALUE))
        );
        ProduitPanelLayout.setVerticalGroup(
            ProduitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProduitPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        ParentPanel.add(ProduitPanel, "card2");

        javax.swing.GroupLayout PanelServiceLayout = new javax.swing.GroupLayout(PanelService);
        PanelService.setLayout(PanelServiceLayout);
        PanelServiceLayout.setHorizontalGroup(
            PanelServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1103, Short.MAX_VALUE)
        );
        PanelServiceLayout.setVerticalGroup(
            PanelServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 542, Short.MAX_VALUE)
        );

        ParentPanel.add(PanelService, "card4");

        javax.swing.GroupLayout PanierReclamationLayout = new javax.swing.GroupLayout(PanierReclamation);
        PanierReclamation.setLayout(PanierReclamationLayout);
        PanierReclamationLayout.setHorizontalGroup(
            PanierReclamationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1103, Short.MAX_VALUE)
        );
        PanierReclamationLayout.setVerticalGroup(
            PanierReclamationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 542, Short.MAX_VALUE)
        );

        ParentPanel.add(PanierReclamation, "card5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ParentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(MenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ParentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProduitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProduitsActionPerformed

        ParentPanel.removeAll();
        ParentPanel.add(ProduitPanel);
        ParentPanel.repaint();
        ParentPanel.revalidate();


    }//GEN-LAST:event_btnProduitsActionPerformed

    private void btnAccueilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccueilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAccueilActionPerformed

    private void tbProduitsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbProduitsMouseClicked

    }//GEN-LAST:event_tbProduitsMouseClicked

    private void btnPartagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPartagerActionPerformed
        int ligneSelectionne = tbProduits.getSelectedRow();
        //on récupére la valeur de la première colonne de la ligne sélectionné

        Object l = tbProduits.getValueAt(ligneSelectionne, 0);

        String accessToken = "CAACEdEose0cBAMDBjsGZBTLZB8BIfLGJGbjs0YZA3tCD3PXrq4sPnLsWYMlcAQzVRESOhmiAcmujhVZAtZAVYGylTOrXfBkHTZAnqsESaJo6Bb1AryqRB08XUmjp2gfvE2W4LJfdhvmJPhyEcFvEIRYgloJgUNcO1tMpOBpAThu7GO7VGaZCYCZCYFZAENcOlfCyUjQJc2qwA9gZDZD";
        FacebookClient fbClient = new DefaultFacebookClient(accessToken);
        User me = fbClient.fetchObject("me", User.class);
        Page userPgae = fbClient.fetchObject("10208045352675324", Page.class);

        System.out.println(me.getName());
        System.out.println(me.getBirthday());

        String nom = (String) tbProduits.getValueAt(ligneSelectionne, 1);
        String categorie = (String) tbProduits.getValueAt(ligneSelectionne, 2);
        int quantite = (int) tbProduits.getValueAt(ligneSelectionne, 3);
        String description = (String) tbProduits.getValueAt(ligneSelectionne, 4);
        float prix = (float) tbProduits.getValueAt(ligneSelectionne, 5);
        int pointBonus = (int) tbProduits.getValueAt(ligneSelectionne, 6);
        String zone = (String) tbProduits.getValueAt(ligneSelectionne, 7);
        Date dateAjout = (Date) tbProduits.getValueAt(ligneSelectionne, 8);
        float TVA = (float) tbProduits.getValueAt(ligneSelectionne, 9);
        float reduction = (float) tbProduits.getValueAt(ligneSelectionne, 10);
        int rating = (int) tbProduits.getValueAt(ligneSelectionne, 11);

        fbClient.publish("10208045352675324" + "/feed", FacebookType.class, Parameter.with("message", "nom du produit : " + nom
            + "\nCategorie : " + categorie + "\nQuantite : " + quantite + "\nDescription : " + description+"\nPrix : "+prix+"\nPoint Bonus: "+pointBonus+"\nGouvernorat : "+zone+"\n Date Ajout :"+dateAjout+"TVA : "+TVA+"\nRéduction : "+reduction+"\rating"+rating ));

    JOptionPane.showMessageDialog(null, "Shared Succefully on Facebook!");
    }//GEN-LAST:event_btnPartagerActionPerformed

    private void btnRechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRechercherActionPerformed
        categorie = cbCategorieR.getSelectedItem().toString();
        System.out.println(categorie);

        pdao.findAllByCategorie(categorie);
        tbRecherche.setModel(new ProduitByCategorieModel());
    }//GEN-LAST:event_btnRechercherActionPerformed

    private void btnAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterActionPerformed
        Produit p = new Produit();
        Date date = new java.sql.Date(System.currentTimeMillis());
        p.setDateAjout(date);
        p.setPrix((float) Double.parseDouble(tfPrix.getText()));
        p.setQuantite(Integer.parseInt(tfQuantite.getText()));
        p.setTva(Integer.parseInt(tfTVA.getText()));
        p.setReduction(Integer.parseInt(tfReduction.getText()));
        p.setNomP(tfNomP.getText());
        p.setCategorie(cbCategorie.getSelectedItem().toString());
        try {
            rsId = zdao.getZoneByName(cbZone.getSelectedItem().toString());
            while (rsId.next()) {
                p.setZone(rsId.getInt(1));

            }//this.setResizable(false);
        } catch (SQLException ex) {
            Logger.getLogger(FrameAjouterService.class.getName()).log(Level.SEVERE, null, ex);
        }
        p.setPtbonus(Integer.parseInt(tfPointBonus.getText()));
        p.setDescription(taDescription.getText());

        PostFile pf = new PostFile();
        String sp = tfPhoto.getText();
        try {
            pf.upload(sp);
            JOptionPane.showMessageDialog(null, "Image telechargé avec succés");
            p.setPhoto("http://localhost/Tec/web/uploads/media/profile/" + im);
        } catch (Exception ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);

        }

        LAlerte.setText(" ");

        if (!tfNomP.getText().trim().equals("")) {
            pdao.add(p);
            tbProduits.setModel(new ProduitModel());
            tblMesProduits.setModel(new ProduitClientModel());
        } else {
            LAlerte.setText("Veuiller introduire le nom de votre produit");
        }
    }//GEN-LAST:event_btnAjouterActionPerformed

    private void tfNomPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomPActionPerformed

    private void cbCategorieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCategorieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCategorieActionPerformed

    private void LAlerteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LAlerteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LAlerteActionPerformed

    private void btnParcourirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParcourirActionPerformed
        JFileChooser chooser = new JFileChooser();

        FileNameExtensionFilter filter = new FileNameExtensionFilter(
            "JPG & GIF Images", "jpg", "gif");
        chooser.setFileFilter(filter);
        int returnVal = chooser.showOpenDialog(btnParcourir);
        if (returnVal == JFileChooser.APPROVE_OPTION) {

            tfPhoto.setText(chooser.getSelectedFile().getAbsolutePath());
            im = chooser.getSelectedFile().getName();
        }
    }//GEN-LAST:event_btnParcourirActionPerformed

    private void tblMesProduitsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMesProduitsMouseClicked
        int i = tblMesProduits.getSelectedRow();
        TableModel model = tblMesProduits.getModel();
        labelId.setText(model.getValueAt(i, 0).toString());
        System.out.println(labelId);
        tfNomP1.setText(model.getValueAt(i, 1).toString());
        cbCategorie1.setSelectedItem(tblMesProduits.getValueAt(i, 2));
        tfQuantite1.setText(model.getValueAt(i, 3).toString());
        taDescription1.setText(model.getValueAt(i, 4).toString());
        tfPrix1.setText(model.getValueAt(i, 5).toString());
        tfPointBonus1.setText(model.getValueAt(i, 6).toString());
        cbZone1.setSelectedItem(tblMesProduits.getValueAt(i, 7));
        tfTVA1.setText(model.getValueAt(i, 9).toString());
    }//GEN-LAST:event_tblMesProduitsMouseClicked

    private void tfNomP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomP1ActionPerformed

    private void tfPointBonus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPointBonus1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPointBonus1ActionPerformed

    private void bntConsulterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntConsulterActionPerformed

        int i = tblMesProduits.getSelectedRow();
        Object l = tblMesProduits.getValueAt(i, 0);
        prod_id = (int) l;
        // System.out.println(prod_id);
        TableModel model = tblMesProduits.getModel();
        // System.out.println(tfNomP1.getText().toString());
        FrameDetailsProduit fDP = new FrameDetailsProduit();
        fDP.tfNomProduit2.setText(tfNomP1.getText());
        fDP.cbCategorie2.setSelectedItem(cbCategorie1.getSelectedItem());
        fDP.tfQuantite2.setText(tfQuantite1.getText());
        fDP.taDescription2.setText(taDescription1.getText());
        fDP.tfPrix2.setText(tfPrix1.getText());
        fDP.tfPointBonus2.setText(tfPointBonus1.getText());
        fDP.cbZone2.setSelectedItem(cbZone1.getSelectedItem());
        fDP.tfTVA2.setText(tfTVA1.getText());
        fDP.tfReduction2.setText(tfReduction1.getText());
        fDP.setVisible(true);

    }//GEN-LAST:event_bntConsulterActionPerformed

    private void btnSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprimerActionPerformed
        FrameGestionProduitClient fGPC = new FrameGestionProduitClient();
        int i = tblMesProduits.getSelectedRow();
        Object l = tblMesProduits.getValueAt(i, 0);

        ProduitDao pdao = new ProduitDao();

        int j = JOptionPane.showConfirmDialog(null, "la suppression est irréversible. Etes-vous sur de vouloir continuer?", "Veuillez confirmer votre choix", JOptionPane.YES_NO_OPTION);

        if (j == 0) {
            pdao.removeById((int) l);

            tblMesProduits.setModel(new ProduitClientModel());

            // jScrollPane2.setViewportView(tblMesProduits);
            tblMesProduits.setModel(new ProduitClientModel());
        }
    }//GEN-LAST:event_btnSupprimerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AllForDealFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AllForDealFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AllForDealFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AllForDealFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AllForDealFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AccueilPanel;
    private javax.swing.JButton AjoutPanier;
    private javax.swing.JButton AjouterProduitPanier;
    private javax.swing.JTextField LAlerte;
    private javax.swing.JPanel MenuPanel;
    private javax.swing.JPanel PanelService;
    private javax.swing.JPanel PanierReclamation;
    private javax.swing.JPanel ParentPanel;
    private javax.swing.JPanel ProduitPanel;
    private javax.swing.JButton bntConsulter;
    private javax.swing.JButton btnAccueil;
    private javax.swing.JButton btnAjouter;
    private javax.swing.JButton btnMessage;
    private javax.swing.JButton btnNotif;
    private javax.swing.JButton btnPanier;
    private javax.swing.JButton btnParcourir;
    private javax.swing.JButton btnPartager;
    private javax.swing.JButton btnProduits;
    private javax.swing.JButton btnProfile;
    private javax.swing.JButton btnRechercher;
    private javax.swing.JButton btnReclam;
    private javax.swing.JButton btnServices;
    private javax.swing.JButton btnSupprimer;
    private javax.swing.JComboBox cbCategorie;
    private javax.swing.JComboBox cbCategorie1;
    private javax.swing.JComboBox cbCategorieR;
    private javax.swing.JComboBox cbZone;
    private javax.swing.JComboBox cbZone1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelId;
    private javax.swing.JLabel lbonus;
    private javax.swing.JLabel lbonus1;
    private javax.swing.JLabel lbonus2;
    private javax.swing.JLabel lbonus3;
    private javax.swing.JLabel lbonus4;
    private javax.swing.JLabel lbonus5;
    private javax.swing.JLabel lcat;
    private javax.swing.JLabel lcat1;
    private javax.swing.JLabel lcat2;
    private javax.swing.JLabel lcat3;
    private javax.swing.JLabel lcat4;
    private javax.swing.JLabel lcat5;
    private javax.swing.JLabel limage;
    private javax.swing.JLabel limage1;
    private javax.swing.JLabel limage2;
    private javax.swing.JLabel limage3;
    private javax.swing.JLabel limage4;
    private javax.swing.JLabel limage5;
    private javax.swing.JLabel lnom;
    private javax.swing.JLabel lnom1;
    private javax.swing.JLabel lnom2;
    private javax.swing.JLabel lnom3;
    private javax.swing.JLabel lnom4;
    private javax.swing.JLabel lnom5;
    private javax.swing.JLabel lprix;
    private javax.swing.JLabel lprix1;
    private javax.swing.JLabel lprix2;
    private javax.swing.JLabel lprix3;
    private javax.swing.JLabel lprix4;
    private javax.swing.JLabel lprix5;
    private javax.swing.JLabel lquantite;
    private javax.swing.JLabel lquantite1;
    private javax.swing.JLabel lquantite2;
    private javax.swing.JLabel lquantite3;
    private javax.swing.JLabel lquantite4;
    private javax.swing.JLabel lquantite5;
    private javax.swing.JPanel p1;
    private javax.swing.JPanel p2;
    private javax.swing.JPanel p3;
    private javax.swing.JPanel p4;
    private javax.swing.JPanel p5;
    private javax.swing.JPanel p6;
    private javax.swing.JTextArea taDescription;
    private javax.swing.JTextArea taDescription1;
    private javax.swing.JTable tbProduits;
    private javax.swing.JTable tbRecherche;
    private javax.swing.JTable tblMesProduits;
    private javax.swing.JTextField tfNomP;
    private javax.swing.JTextField tfNomP1;
    private javax.swing.JTextField tfPhoto;
    private javax.swing.JTextField tfPointBonus;
    private javax.swing.JTextField tfPointBonus1;
    private javax.swing.JTextField tfPrix;
    private javax.swing.JTextField tfPrix1;
    private javax.swing.JTextField tfQuantite;
    private javax.swing.JTextField tfQuantite1;
    private javax.swing.JTextField tfReduction;
    private javax.swing.JTextField tfReduction1;
    private javax.swing.JTextField tfTVA;
    private javax.swing.JTextField tfTVA1;
    // End of variables declaration//GEN-END:variables
}
