/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import dao.ProduitDao;
import dao.ZoneDao;
import entite.Produit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import utils.ProduitModel;

/**
 *
 * @author esprit
 */
public class FrameGestionProduitAdmin extends javax.swing.JFrame {
    
    
    

    ResultSet rsNom = null;
    public static int prod_id;
    ProduitDao pdao = new ProduitDao();
    ZoneDao zdao = new ZoneDao();

    public static int getProd_id() {
        return prod_id;
    }

    public static void setProd_id(int prod_id) {
        FrameGestionProduitAdmin.prod_id = prod_id;
    }

    /**
     * Creates new form FrameGestionProduitAdmin
     */
    public FrameGestionProduitAdmin() {
        initComponents();
        labelId.setVisible(false);
        loadAllCollection();
        loadAllVille();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ParentPanel = new javax.swing.JPanel();
        ListeProduits = new javax.swing.JPanel();
        tfNomProduit = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfPrix = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbCategorie = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        tfTVA = new javax.swing.JTextField();
        tfReduction = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfQuantite = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cbZone = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tfPointBonus = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        taDescription = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbProduits = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnConsulter = new javax.swing.JButton();
        btnSupprimer = new javax.swing.JButton();
        labelId = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        DetailsProduit = new javax.swing.JPanel();
        tfNomProduit1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tfPrix1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cbCategorie1 = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        tfTVA1 = new javax.swing.JTextField();
        tfReduction1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        tfQuantite1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        btnAnnuler = new javax.swing.JButton();
        cbZone1 = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        tfPointBonus1 = new javax.swing.JTextField();
        btnEffacer = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        taDescription1 = new javax.swing.JTextArea();
        jLabel19 = new javax.swing.JLabel();
        btnPrecedant = new javax.swing.JButton();
        btnModifier = new javax.swing.JButton();
        lMsg = new javax.swing.JLabel();
        BtnAime = new javax.swing.JButton();
        BtnAimepas = new javax.swing.JButton();
        rb2 = new javax.swing.JRadioButton();
        rb1 = new javax.swing.JRadioButton();
        rb3 = new javax.swing.JRadioButton();
        rb4 = new javax.swing.JRadioButton();
        rb5 = new javax.swing.JRadioButton();
        btnVote = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ParentPanel.setLayout(new java.awt.CardLayout());

        ListeProduits.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tfNomProduit.setEditable(false);
        tfNomProduit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomProduitActionPerformed(evt);
            }
        });

        jLabel2.setText("Nom du Produit");

        tfPrix.setEditable(false);
        tfPrix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPrixActionPerformed(evt);
            }
        });
        tfPrix.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfPrixKeyTyped(evt);
            }
        });

        jLabel3.setText("Catégorie");

        jLabel4.setText("Prix");

        jLabel5.setText("TVA");

        tfTVA.setEditable(false);
        tfTVA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTVAActionPerformed(evt);
            }
        });
        tfTVA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfTVAKeyTyped(evt);
            }
        });

        tfReduction.setEditable(false);
        tfReduction.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfReductionKeyTyped(evt);
            }
        });

        jLabel6.setText("Réduction");

        tfQuantite.setEditable(false);
        tfQuantite.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfQuantiteKeyTyped(evt);
            }
        });

        jLabel7.setText("Quantité");

        jLabel8.setText("Gouvernorat");

        jLabel9.setText("Point Bonus");

        tfPointBonus.setEditable(false);
        tfPointBonus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPointBonusActionPerformed(evt);
            }
        });
        tfPointBonus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfPointBonusKeyTyped(evt);
            }
        });

        taDescription.setColumns(20);
        taDescription.setRows(5);
        jScrollPane2.setViewportView(taDescription);

        jLabel10.setText("Description");

        tbProduits.setModel(new ProduitModel());
        tbProduits.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbProduitsMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbProduits);

        jLabel1.setFont(new java.awt.Font("Simplified Arabic", 1, 18)); // NOI18N
        jLabel1.setText("Explorateur des produits");

        btnConsulter.setText("Consulter");
        btnConsulter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsulterActionPerformed(evt);
            }
        });

        btnSupprimer.setText("Supprimer");
        btnSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprimerActionPerformed(evt);
            }
        });

        jButton1.setText("j'aime");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ListeProduitsLayout = new javax.swing.GroupLayout(ListeProduits);
        ListeProduits.setLayout(ListeProduitsLayout);
        ListeProduitsLayout.setHorizontalGroup(
            ListeProduitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListeProduitsLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(ListeProduitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ListeProduitsLayout.createSequentialGroup()
                        .addGroup(ListeProduitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ListeProduitsLayout.createSequentialGroup()
                                .addGroup(ListeProduitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGap(164, 164, 164))
                            .addGroup(ListeProduitsLayout.createSequentialGroup()
                                .addGroup(ListeProduitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ListeProduitsLayout.createSequentialGroup()
                                        .addGap(120, 120, 120)
                                        .addGroup(ListeProduitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfPrix, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbCategorie, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfNomProduit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ListeProduitsLayout.createSequentialGroup()
                                        .addGroup(ListeProduitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(ListeProduitsLayout.createSequentialGroup()
                                                .addGroup(ListeProduitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel9)
                                                    .addComponent(jLabel7)
                                                    .addComponent(jLabel6)
                                                    .addComponent(jLabel8)
                                                    .addComponent(jLabel5)
                                                    .addComponent(jLabel10))
                                                .addGap(47, 47, 47)
                                                .addGroup(ListeProduitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(tfTVA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(tfReduction, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(tfQuantite, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(tfPointBonus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(cbZone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(ListeProduitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(ListeProduitsLayout.createSequentialGroup()
                                                    .addComponent(btnConsulter)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(btnSupprimer))
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(2, 2, 2)))
                                .addGap(33, 33, 33)))
                        .addGroup(ListeProduitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
                            .addGroup(ListeProduitsLayout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(jButton1)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(ListeProduitsLayout.createSequentialGroup()
                        .addComponent(labelId, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(246, 246, 246)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ListeProduitsLayout.setVerticalGroup(
            ListeProduitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListeProduitsLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(ListeProduitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(ListeProduitsLayout.createSequentialGroup()
                        .addComponent(labelId, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ListeProduitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ListeProduitsLayout.createSequentialGroup()
                        .addGroup(ListeProduitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ListeProduitsLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel2))
                            .addComponent(tfNomProduit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ListeProduitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(cbCategorie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(ListeProduitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfPrix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(ListeProduitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbZone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(ListeProduitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tfTVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ListeProduitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfReduction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ListeProduitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfQuantite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ListeProduitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfPointBonus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(ListeProduitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSupprimer)
                    .addComponent(btnConsulter)
                    .addComponent(jButton1))
                .addGap(19, 19, 19))
        );

        ParentPanel.add(ListeProduits, "card2");

        DetailsProduit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tfNomProduit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomProduit1ActionPerformed(evt);
            }
        });

        jLabel11.setText("Nom du Produit");

        tfPrix1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPrix1ActionPerformed(evt);
            }
        });
        tfPrix1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfPrix1KeyTyped(evt);
            }
        });

        jLabel12.setText("Catégorie");

        jLabel13.setText("Prix");

        jLabel14.setText("TVA");

        tfTVA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTVA1ActionPerformed(evt);
            }
        });
        tfTVA1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfTVA1KeyTyped(evt);
            }
        });

        tfReduction1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfReduction1KeyTyped(evt);
            }
        });

        jLabel15.setText("Réduction");

        tfQuantite1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfQuantite1KeyTyped(evt);
            }
        });

        jLabel16.setText("Quantité");

        btnAnnuler.setText("Annuler");
        btnAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnnulerActionPerformed(evt);
            }
        });

        jLabel17.setText("Gouvernorat");

        jLabel18.setText("Point Bonus");

        tfPointBonus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPointBonus1ActionPerformed(evt);
            }
        });
        tfPointBonus1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfPointBonus1KeyTyped(evt);
            }
        });

        btnEffacer.setText("Effacer");
        btnEffacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEffacerActionPerformed(evt);
            }
        });

        taDescription1.setColumns(20);
        taDescription1.setRows(5);
        jScrollPane4.setViewportView(taDescription1);

        jLabel19.setText("Description");

        btnPrecedant.setText("Précédant");
        btnPrecedant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrecedantActionPerformed(evt);
            }
        });

        btnModifier.setText("Modifier");
        btnModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierActionPerformed(evt);
            }
        });

        lMsg.setText("jLabel20");

        BtnAime.setText("J'aime");
        BtnAime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAimeActionPerformed(evt);
            }
        });

        BtnAimepas.setText("J'aime pas");
        BtnAimepas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAimepasActionPerformed(evt);
            }
        });

        rb2.setText("jRadioButton1");

        rb1.setText("jRadioButton2");

        rb3.setText("jRadioButton3");

        rb4.setText("jRadioButton4");

        rb5.setText("jRadioButton5");

        btnVote.setText("Vote");
        btnVote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DetailsProduitLayout = new javax.swing.GroupLayout(DetailsProduit);
        DetailsProduit.setLayout(DetailsProduitLayout);
        DetailsProduitLayout.setHorizontalGroup(
            DetailsProduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DetailsProduitLayout.createSequentialGroup()
                .addGroup(DetailsProduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DetailsProduitLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(DetailsProduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15)
                            .addComponent(jLabel17)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14))
                        .addGroup(DetailsProduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DetailsProduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfPrix1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbZone1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(DetailsProduitLayout.createSequentialGroup()
                                    .addGap(47, 47, 47)
                                    .addGroup(DetailsProduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cbCategorie1, javax.swing.GroupLayout.Alignment.TRAILING, 0, 84, Short.MAX_VALUE)
                                        .addComponent(tfNomProduit1, javax.swing.GroupLayout.Alignment.TRAILING))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DetailsProduitLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(DetailsProduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnEffacer)
                                    .addGroup(DetailsProduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tfTVA1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tfReduction1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tfQuantite1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tfPointBonus1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(DetailsProduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DetailsProduitLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel19))
                            .addGroup(DetailsProduitLayout.createSequentialGroup()
                                .addGroup(DetailsProduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, DetailsProduitLayout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(btnAnnuler)
                                        .addGap(48, 48, 48)
                                        .addComponent(btnPrecedant)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnModifier))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, DetailsProduitLayout.createSequentialGroup()
                                        .addGap(77, 77, 77)
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(27, 27, 27)
                                .addComponent(BtnAime)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BtnAimepas))
                            .addGroup(DetailsProduitLayout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addGroup(DetailsProduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rb2)
                                    .addComponent(rb1)))
                            .addGroup(DetailsProduitLayout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addGroup(DetailsProduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rb4)
                                    .addGroup(DetailsProduitLayout.createSequentialGroup()
                                        .addComponent(rb3)
                                        .addGap(70, 70, 70)
                                        .addComponent(btnVote))
                                    .addComponent(rb5)))))
                    .addGroup(DetailsProduitLayout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(lMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        DetailsProduitLayout.setVerticalGroup(
            DetailsProduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DetailsProduitLayout.createSequentialGroup()
                .addGroup(DetailsProduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DetailsProduitLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(DetailsProduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfNomProduit1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(DetailsProduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(cbCategorie1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(DetailsProduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfPrix1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(DetailsProduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbZone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addGroup(DetailsProduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(tfTVA1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(DetailsProduitLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DetailsProduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfReduction1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGroup(DetailsProduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DetailsProduitLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(DetailsProduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfQuantite1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(rb1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(DetailsProduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfPointBonus1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)))
                    .addGroup(DetailsProduitLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(rb2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(DetailsProduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rb3)
                            .addComponent(btnVote))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rb4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rb5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(DetailsProduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEffacer)
                    .addComponent(btnAnnuler)
                    .addComponent(btnPrecedant)
                    .addComponent(btnModifier)
                    .addComponent(BtnAime)
                    .addComponent(BtnAimepas))
                .addGap(47, 47, 47))
        );

        ParentPanel.add(DetailsProduit, "card3");

        getContentPane().add(ParentPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfNomProduitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomProduitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomProduitActionPerformed

    private void tfPrixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPrixActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPrixActionPerformed

    private void tfPrixKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPrixKeyTyped

    }//GEN-LAST:event_tfPrixKeyTyped

    private void tfTVAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTVAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTVAActionPerformed

    private void tfTVAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfTVAKeyTyped

    }//GEN-LAST:event_tfTVAKeyTyped

    private void tfReductionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfReductionKeyTyped

    }//GEN-LAST:event_tfReductionKeyTyped

    private void tfQuantiteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfQuantiteKeyTyped

    }//GEN-LAST:event_tfQuantiteKeyTyped

    private void tfPointBonusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPointBonusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPointBonusActionPerformed

    private void tfPointBonusKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPointBonusKeyTyped

    }//GEN-LAST:event_tfPointBonusKeyTyped

    private void tbProduitsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbProduitsMouseClicked
        int i = tbProduits.getSelectedRow();
        TableModel model = tbProduits.getModel();
        labelId.setText(model.getValueAt(i, 0).toString());
        System.out.println(labelId);
        tfNomProduit.setText(model.getValueAt(i, 1).toString());
        cbCategorie.setSelectedItem(model.getValueAt(i, 2).toString());
        tfQuantite.setText(model.getValueAt(i, 3).toString());
        taDescription.setText(model.getValueAt(i, 4).toString());
        tfPrix.setText(model.getValueAt(i, 5).toString());
        tfPointBonus.setText(model.getValueAt(i, 6).toString());
        cbZone.setSelectedItem(model.getValueAt(i, 7).toString());
        tfTVA.setText(model.getValueAt(i, 9).toString());
        tfReduction.setText(model.getValueAt(i, 10).toString());

    }//GEN-LAST:event_tbProduitsMouseClicked

    private void btnConsulterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsulterActionPerformed

        int i = tbProduits.getSelectedRow();
        Object l = tbProduits.getValueAt(i, 0);
        prod_id = (int) l;
        System.out.println(prod_id);
        TableModel model = tbProduits.getModel();
//        tfNomProduit1.setText(tfNomProduit.getText());
//        cbCategorie1.setSelectedItem(cbCategorie.getSelectedItem());
//        tfQuantite1.setText(tfQuantite.getText());
//        taDescription1.setText(taDescription.getText());
//        tfPrix1.setText(tfPrix.getText());
//        tfPointBonus1.setText(tfPointBonus.getText());
//        cbZone1.setSelectedItem(cbZone.getSelectedItem());
//        tfTVA1.setText(tfTVA.getText());
//        tfReduction1.setText(tfReduction.getText());
//
//        ParentPanel.removeAll();
//        ParentPanel.add(DetailsProduit);
//        ParentPanel.repaint();
//        ParentPanel.revalidate();

        FrameDetailsProduit fe =new FrameDetailsProduit();
        fe.setVisible(true);

    }//GEN-LAST:event_btnConsulterActionPerformed

    private void tfNomProduit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomProduit1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomProduit1ActionPerformed

    private void tfPrix1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPrix1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPrix1ActionPerformed

    private void tfPrix1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPrix1KeyTyped

    }//GEN-LAST:event_tfPrix1KeyTyped

    private void tfTVA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTVA1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTVA1ActionPerformed

    private void tfTVA1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfTVA1KeyTyped

    }//GEN-LAST:event_tfTVA1KeyTyped

    private void tfReduction1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfReduction1KeyTyped

    }//GEN-LAST:event_tfReduction1KeyTyped

    private void tfQuantite1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfQuantite1KeyTyped

    }//GEN-LAST:event_tfQuantite1KeyTyped

    private void btnAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnnulerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAnnulerActionPerformed

    private void tfPointBonus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPointBonus1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPointBonus1ActionPerformed

    private void tfPointBonus1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPointBonus1KeyTyped

    }//GEN-LAST:event_tfPointBonus1KeyTyped

    private void btnEffacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEffacerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEffacerActionPerformed

    private void btnPrecedantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrecedantActionPerformed
        ParentPanel.removeAll();
        ParentPanel.add(ListeProduits);
        ParentPanel.repaint();
        ParentPanel.revalidate();
    }//GEN-LAST:event_btnPrecedantActionPerformed

    private void btnSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprimerActionPerformed
        FrameListerProduits frameListeProduits = new FrameListerProduits();
        int i = tbProduits.getSelectedRow();
        Object l = tbProduits.getValueAt(i, 0);

        ProduitDao pdao = new ProduitDao();

        int j = JOptionPane.showConfirmDialog(null, "la suppression est irréversible. Etes-vous sur de vouloir continuer?", "Veuillez confirmer votre choix", JOptionPane.YES_NO_OPTION);

        if (j == 0) {
            pdao.removeById((int) l);

            tbProduits.setModel(new ProduitModel());

            jScrollPane2.setViewportView(tbProduits);

        }
    }//GEN-LAST:event_btnSupprimerActionPerformed

    private void btnModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierActionPerformed
        lMsg.setText(" ");

        Produit p = new Produit();
        Date date = new java.sql.Date(System.currentTimeMillis());
        if (!tfNomProduit1.getText().trim().equals("")) {
            p.setId(Integer.parseInt(labelId.getText()));
            p.setNomP(tfNomProduit1.getText());
            p.setQuantite(Integer.parseInt(tfQuantite1.getText()));
            p.setDescription(taDescription1.getText());
            p.setCategorie(cbCategorie1.getSelectedItem().toString());
            try {
                rsNom = zdao.getZoneByName(cbZone.getSelectedItem().toString());
                while (rsNom.next()) {
                    p.setZone(rsNom.getInt(1));
                    System.out.println(rsNom.getInt(1));
                }//this.setResizable(false);
            } catch (SQLException ex) {
                Logger.getLogger(FrameAjouterService.class.getName()).log(Level.SEVERE, null, ex);
            }
            p.setDateAjout(date);
            p.setPrix(Integer.parseInt(tfPrix1.getText()));
            p.setPtbonus(Integer.parseInt(tfPointBonus1.getText()));
            p.setReduction(Integer.parseInt(tfReduction1.getText()));
            p.setTva(Integer.parseInt(tfTVA1.getText()));

            pdao.update(p);

        } else {
            lMsg.setText(" Veuiller enter le nom de votre service SVP !");
        }
        tbProduits.setModel(new ProduitModel()); // Act tab apres modif
    }//GEN-LAST:event_btnModifierActionPerformed

    private void BtnAimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAimeActionPerformed

        Produit prod = new Produit();
        ProduitDao pdao = new ProduitDao();
        prod = pdao.findById(prod_id);
        pdao.updateRating(prod);
        BtnAime.setVisible(false);
    }//GEN-LAST:event_BtnAimeActionPerformed

    private void BtnAimepasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAimepasActionPerformed
        Produit prod = new Produit();
        ProduitDao pdao = new ProduitDao();
        prod = pdao.findById(prod_id);
        prod.setRating(prod.getRating() - 1);
        pdao.update(prod);
        BtnAimepas.setVisible(false);
    }//GEN-LAST:event_BtnAimepasActionPerformed

    private void btnVoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoteActionPerformed
      int v; 
      ProduitDao pdao=new ProduitDao();
if(rb1.isSelected()){
   v=1;// TODO add your handling code here:
   if(rb2.isSelected()){
   v=2;// TODO add your handling code here:
    }                                       
if(rb3.isSelected()){
   v=3;// TODO add your handling code here:
    }                                       
if(rb4.isSelected()){
   v=4;// TODO add your handling code here:
    }                                       
if(rb5.isSelected()){
   v=5;// TODO add your handling code here:
    }
   
    }
    }//GEN-LAST:event_btnVoteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        //BtnAimepas.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        Produit prod = new Produit();
        ProduitDao pdao = new ProduitDao();
        prod = pdao.findById(prod_id);
         System.out.println(prod.getRating());
        prod.setRating(prod.getRating() +1);
        pdao.updateRating(prod);
          System.out.println(prod.getRating());
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameGestionProduitAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameGestionProduitAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameGestionProduitAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameGestionProduitAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameGestionProduitAdmin().setVisible(true);
            }
        });
    }

    private void loadAllVille() {
        try {
            ResultSet res = zdao.getAllVille();

            while (res.next()) {

                cbZone.addItem(res.getString(1));
                // System.out.println(res.getString(1));

            }
        } catch (SQLException ex) {
            Logger.getLogger(FrameAjouterProduit.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadAllCollection() {
        try {
            ResultSet res = pdao.getCategories();

            while (res.next()) {

                cbCategorie.addItem(res.getString(1));
                // System.out.println(res.getString(1));

            }
        } catch (SQLException ex) {
            Logger.getLogger(FrameAjouterProduit.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAime;
    private javax.swing.JButton BtnAimepas;
    private javax.swing.JPanel DetailsProduit;
    private javax.swing.JPanel ListeProduits;
    private javax.swing.JPanel ParentPanel;
    private javax.swing.JButton btnAnnuler;
    private javax.swing.JButton btnConsulter;
    private javax.swing.JButton btnEffacer;
    private javax.swing.JButton btnModifier;
    private javax.swing.JButton btnPrecedant;
    private javax.swing.JButton btnSupprimer;
    private javax.swing.JButton btnVote;
    private javax.swing.JComboBox cbCategorie;
    private javax.swing.JComboBox cbCategorie1;
    private javax.swing.JComboBox cbZone;
    private javax.swing.JComboBox cbZone1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lMsg;
    private javax.swing.JLabel labelId;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JRadioButton rb3;
    private javax.swing.JRadioButton rb4;
    private javax.swing.JRadioButton rb5;
    private javax.swing.JTextArea taDescription;
    private javax.swing.JTextArea taDescription1;
    private javax.swing.JTable tbProduits;
    private javax.swing.JTextField tfNomProduit;
    private javax.swing.JTextField tfNomProduit1;
    private javax.swing.JTextField tfPointBonus;
    private javax.swing.JTextField tfPointBonus1;
    private javax.swing.JTextField tfPrix;
    private javax.swing.JTextField tfPrix1;
    private javax.swing.JTextField tfQuantite;
    private javax.swing.JTextField tfQuantite1;
    private javax.swing.JTextField tfReduction;
    private javax.swing.JTextField tfReduction1;
    private javax.swing.JTextField tfTVA;
    private javax.swing.JTextField tfTVA1;
    // End of variables declaration//GEN-END:variables
}
