/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import static GUI.FrameGestionProduitAdmin.prod_id;
import dao.CommentDao;
import utils.*;
import dao.ServiceDao;
import dao.ZoneDao;
import entite.Comment;
import entite.Service;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.lang.annotation.RetentionPolicy;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Super
 */
public class FrameAfficherServiceAll extends javax.swing.JFrame {

    Toolkit tk = Toolkit.getDefaultToolkit();
    Dimension screenSize = tk.getScreenSize();
    int screenHeight = screenSize.height;
    int screenWidth = screenSize.width;

    //private static int categorie;
    private static int service_id;
    private Connection conn = null;
    private PreparedStatement pst = null;
    ResultSet rs = null;
    ResultSet rsNom = null;
    ResultSet rsId = null;
    ServiceDao pdao = new ServiceDao();
    ZoneDao zoneDAO = new ZoneDao();
    private static String categorie;

    public static String getCategorie() {
        return categorie;
    }

    public static void setUserId(int user_id) {
        FrameAfficherServiceAll.categorie = categorie;
    }

    public static int getService_id() {
        return service_id;
    }

    public static void setService_id(int service_id) {
        FrameAfficherServiceAll.service_id = service_id;
    }

    /**
     * Creates new form FrameAfficherServiceAll
     */
    public FrameAfficherServiceAll() {
        initComponents();
        loadAllVille();
        loadAllCategorie();
        labelId.setVisible(false);
        tbCommentService.setModel(new CommentSModel());
        tbCommentService.setVisible(true);
        //  pConsulterS.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpService = new javax.swing.JTabbedPane();
        pAjoutS = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfNomS = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfDescription = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbCat = new javax.swing.JComboBox();
        cbZone = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        btnAjoutS = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblService = new javax.swing.JTable();
        lerror = new javax.swing.JLabel();
        ParentPanel2 = new javax.swing.JPanel();
        pAllServices = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAllServices = new javax.swing.JTable();
        btnConsulterS1 = new javax.swing.JButton();
        pConsulterS2 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        tfNomService3 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        tfDescription4 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        cbCat4 = new javax.swing.JComboBox();
        cbEtat3 = new javax.swing.JComboBox();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        cbZone4 = new javax.swing.JComboBox();
        btnBackS2 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbCommentService = new javax.swing.JTable();
        btnCommenter = new javax.swing.JButton();
        tfComment = new javax.swing.JTextField();
        btnModifierCommentaire = new javax.swing.JButton();
        btnSupprimerCommentaire = new javax.swing.JButton();
        ParentPanel = new javax.swing.JPanel();
        pMesServices = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblMesServices = new javax.swing.JTable();
        lMsg = new javax.swing.JLabel();
        btnModifier = new javax.swing.JButton();
        bntSupprimer = new javax.swing.JButton();
        cbZone1 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbEtat = new javax.swing.JComboBox();
        cbCat1 = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tfDescription1 = new javax.swing.JTextField();
        tfNomService = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        labelId = new javax.swing.JLabel();
        btnConsulterS = new javax.swing.JButton();
        pConsulterS = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        tfNomService1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tfDescription2 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        cbCat2 = new javax.swing.JComboBox();
        cbEtat1 = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        cbZone2 = new javax.swing.JComboBox();
        btnBackS = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        tbCommentMesServices = new javax.swing.JTable();
        tfCommentS = new javax.swing.JTextField();
        btnCommentS = new javax.swing.JButton();
        btnModifierCommentS = new javax.swing.JButton();
        btnSupprimerCommentS = new javax.swing.JButton();
        pRechercheS = new javax.swing.JPanel();
        lTitreRechercheS = new javax.swing.JLabel();
        cbRechercheCat = new javax.swing.JComboBox();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblRechercheS = new javax.swing.JTable();
        bntRechercheS = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tpService.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tpServiceMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 102));
        jLabel5.setText("Ajouter Un Service");

        jLabel2.setText("Nom Service :");

        tfNomS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomSActionPerformed(evt);
            }
        });

        jLabel3.setText("Description :");

        tfDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDescriptionActionPerformed(evt);
            }
        });

        jLabel4.setText("Catégorie :");

        cbCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCatActionPerformed(evt);
            }
        });

        cbZone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbZoneActionPerformed(evt);
            }
        });

        jLabel6.setText("Gouvernorat :");

        btnAjoutS.setBackground(new java.awt.Color(255, 204, 204));
        btnAjoutS.setText("Ajouter Service");
        btnAjoutS.setAlignmentX(10.1F);
        btnAjoutS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjoutSActionPerformed(evt);
            }
        });

        tblService.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nom Service", "Description", "Catégorie", "Date d'ajout", "Etat"
            }
        ));
        tblService.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblServiceMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblService);

        javax.swing.GroupLayout pAjoutSLayout = new javax.swing.GroupLayout(pAjoutS);
        pAjoutS.setLayout(pAjoutSLayout);
        pAjoutSLayout.setHorizontalGroup(
            pAjoutSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAjoutSLayout.createSequentialGroup()
                .addGroup(pAjoutSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(pAjoutSLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(pAjoutSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)))
                    .addComponent(btnAjoutS, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pAjoutSLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(pAjoutSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbCat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfDescription)
                            .addComponent(tfNomS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbZone, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(pAjoutSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pAjoutSLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel5))
                    .addGroup(pAjoutSLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lerror, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pAjoutSLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pAjoutSLayout.setVerticalGroup(
            pAjoutSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAjoutSLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel5)
                .addGap(47, 47, 47)
                .addComponent(jLabel2)
                .addGap(7, 7, 7)
                .addGroup(pAjoutSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pAjoutSLayout.createSequentialGroup()
                        .addComponent(tfNomS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3)
                        .addGap(4, 4, 4)
                        .addComponent(tfDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel4)
                        .addGap(2, 2, 2)
                        .addComponent(cbCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel6)
                        .addGap(9, 9, 9)
                        .addComponent(cbZone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(btnAjoutS, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lerror, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(141, 141, 141))
        );

        tpService.addTab("Ajouter Un Service", pAjoutS);

        ParentPanel2.setLayout(new java.awt.CardLayout());

        pAllServices.setLayout(null);

        tblAllServices.setModel((new ListeService()));
        tblAllServices.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAllServicesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblAllServices);

        pAllServices.add(jScrollPane2);
        jScrollPane2.setBounds(55, 11, 452, 402);

        btnConsulterS1.setText("Consulter");
        btnConsulterS1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConsulterS1MouseClicked(evt);
            }
        });
        btnConsulterS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsulterS1ActionPerformed(evt);
            }
        });
        pAllServices.add(btnConsulterS1);
        btnConsulterS1.setBounds(50, 450, 79, 23);

        ParentPanel2.add(pAllServices, "card3");

        jLabel22.setText("Nom Service :");

        tfNomService3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomService3ActionPerformed(evt);
            }
        });

        jLabel23.setText("Description :");

        jLabel24.setText("Catégorie :");

        cbCat4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCat4ActionPerformed(evt);
            }
        });

        cbEtat3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "EnCours", "n'est Plus valide" }));

        jLabel25.setText("Etat :");

        jLabel26.setText("Zone :");

        btnBackS2.setText("Back");
        btnBackS2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackS2ActionPerformed(evt);
            }
        });

        tbCommentService.setModel( new CommentSModel());
        tbCommentService.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbCommentServiceMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tbCommentService);

        btnCommenter.setText("Commenter");
        btnCommenter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCommenterActionPerformed(evt);
            }
        });

        tfComment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCommentActionPerformed(evt);
            }
        });

        btnModifierCommentaire.setText("Modifier");
        btnModifierCommentaire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierCommentaireActionPerformed(evt);
            }
        });

        btnSupprimerCommentaire.setText("Supprimer");
        btnSupprimerCommentaire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprimerCommentaireActionPerformed(evt);
            }
        });

        pConsulterS2.add(jScrollPane5);
        jScrollPane5.setBounds(55, 11, 452, 402);

        javax.swing.GroupLayout pConsulterS2Layout = new javax.swing.GroupLayout(pConsulterS2);
        pConsulterS2.setLayout(pConsulterS2Layout);
        pConsulterS2Layout.setHorizontalGroup(
            pConsulterS2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pConsulterS2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(pConsulterS2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addGroup(pConsulterS2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel23)
                        .addGroup(pConsulterS2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(jLabel24)
                            .addComponent(jLabel26))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pConsulterS2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfDescription4, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNomService3, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbCat4, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbEtat3, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbZone4, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pConsulterS2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pConsulterS2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pConsulterS2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                            .addComponent(tfComment))
                        .addGap(76, 76, 76))
                    .addGroup(pConsulterS2Layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addGroup(pConsulterS2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnBackS2)
                            .addGroup(pConsulterS2Layout.createSequentialGroup()
                                .addComponent(btnCommenter)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnModifierCommentaire, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSupprimerCommentaire)))
                        .addContainerGap(84, Short.MAX_VALUE))))
        );
        pConsulterS2Layout.setVerticalGroup(
            pConsulterS2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pConsulterS2Layout.createSequentialGroup()
                .addGroup(pConsulterS2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pConsulterS2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(pConsulterS2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pConsulterS2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cbEtat3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfComment, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pConsulterS2Layout.createSequentialGroup()
                                .addGroup(pConsulterS2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pConsulterS2Layout.createSequentialGroup()
                                        .addGroup(pConsulterS2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(tfNomService3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel22))
                                        .addGroup(pConsulterS2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(pConsulterS2Layout.createSequentialGroup()
                                                .addGap(40, 40, 40)
                                                .addComponent(jLabel23))
                                            .addGroup(pConsulterS2Layout.createSequentialGroup()
                                                .addGap(53, 53, 53)
                                                .addComponent(tfDescription4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(55, 55, 55)
                                        .addGroup(pConsulterS2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel24)
                                            .addComponent(cbCat4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(50, 50, 50)
                                .addComponent(jLabel25)))
                        .addGap(33, 33, 33)
                        .addGroup(pConsulterS2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel26)
                            .addComponent(cbZone4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pConsulterS2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pConsulterS2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCommenter)
                            .addComponent(btnModifierCommentaire)
                            .addComponent(btnSupprimerCommentaire))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGap(40, 40, 40)
                .addComponent(btnBackS2)
                .addGap(111, 111, 111))
        );

        ParentPanel2.add(pConsulterS2, "card3");

        tpService.addTab("Les offres", ParentPanel2);

        ParentPanel.setLayout(new java.awt.CardLayout());

        pMesServices.setLayout(null);

        tblMesServices.setModel((new ServiceByUserIdModel()));
        tblMesServices.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMesServicesMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblMesServices);

        pMesServices.add(jScrollPane3);
        jScrollPane3.setBounds(353, 11, 452, 402);
        pMesServices.add(lMsg);
        lMsg.setBounds(337, 470, 150, 57);

        btnModifier.setText("Modifier");
        btnModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierActionPerformed(evt);
            }
        });
        pMesServices.add(btnModifier);
        btnModifier.setBounds(34, 437, 71, 23);

        bntSupprimer.setText("Supprimer");
        bntSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSupprimerActionPerformed(evt);
            }
        });
        pMesServices.add(bntSupprimer);
        bntSupprimer.setBounds(140, 437, 81, 23);

        pMesServices.add(cbZone1);
        cbZone1.setBounds(80, 367, 156, 20);

        jLabel7.setText("Zone :");
        pMesServices.add(jLabel7);
        jLabel7.setBounds(16, 373, 31, 14);

        jLabel8.setText("Etat :");
        pMesServices.add(jLabel8);
        jLabel8.setBounds(16, 320, 27, 14);

        cbEtat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "EnCours", "n'est Plus valide" }));
        pMesServices.add(cbEtat);
        cbEtat.setBounds(80, 314, 156, 20);

        pMesServices.add(cbCat1);
        cbCat1.setBounds(80, 250, 156, 20);

        jLabel9.setText("Catégorie :");
        pMesServices.add(jLabel9);
        jLabel9.setBounds(16, 253, 54, 14);

        jLabel10.setText("Description :");
        pMesServices.add(jLabel10);
        jLabel10.setBounds(10, 120, 60, 14);
        pMesServices.add(tfDescription1);
        tfDescription1.setBounds(80, 133, 156, 62);

        tfNomService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomServiceActionPerformed(evt);
            }
        });
        pMesServices.add(tfNomService);
        tfNomService.setBounds(80, 60, 156, 20);

        jLabel11.setText("Nom Service :");
        pMesServices.add(jLabel11);
        jLabel11.setBounds(10, 63, 66, 14);

        labelId.setText("ID");
        pMesServices.add(labelId);
        labelId.setBounds(10, 28, 11, 14);

        btnConsulterS.setText("Consulter");
        btnConsulterS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConsulterSMouseClicked(evt);
            }
        });
        btnConsulterS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsulterSActionPerformed(evt);
            }
        });
        pMesServices.add(btnConsulterS);
        btnConsulterS.setBounds(254, 437, 79, 23);

        ParentPanel.add(pMesServices, "card2");

        jLabel12.setText("Nom Service :");

        tfNomService1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomService1ActionPerformed(evt);
            }
        });

        jLabel13.setText("Description :");

        jLabel14.setText("Catégorie :");

        cbCat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCat2ActionPerformed(evt);
            }
        });

        cbEtat1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "EnCours", "n'est Plus valide" }));

        jLabel15.setText("Etat :");

        jLabel16.setText("Zone :");

        btnBackS.setText("Back");
        btnBackS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackSActionPerformed(evt);
            }
        });

        tbCommentMesServices.setModel(new CommentSModel());
        tbCommentMesServices.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbCommentMesServicesMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tbCommentMesServices);

        btnCommentS.setText("Commenter");
        btnCommentS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCommentSActionPerformed(evt);
            }
        });

        btnModifierCommentS.setText("Modifier");
        btnModifierCommentS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierCommentSActionPerformed(evt);
            }
        });

        btnSupprimerCommentS.setText("Supprimer");
        btnSupprimerCommentS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprimerCommentSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pConsulterSLayout = new javax.swing.GroupLayout(pConsulterS);
        pConsulterS.setLayout(pConsulterSLayout);
        pConsulterSLayout.setHorizontalGroup(
            pConsulterSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pConsulterSLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(pConsulterSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(pConsulterSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel13)
                        .addGroup(pConsulterSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14)
                            .addComponent(jLabel16))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pConsulterSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pConsulterSLayout.createSequentialGroup()
                        .addGroup(pConsulterSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbEtat1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pConsulterSLayout.createSequentialGroup()
                                .addComponent(cbZone2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(116, 116, 116)
                                .addComponent(btnCommentS)
                                .addGap(39, 39, 39)
                                .addComponent(btnModifierCommentS)
                                .addGap(32, 32, 32)
                                .addComponent(btnSupprimerCommentS)))
                        .addContainerGap(54, Short.MAX_VALUE))
                    .addGroup(pConsulterSLayout.createSequentialGroup()
                        .addGroup(pConsulterSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbCat2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfDescription2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNomService1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pConsulterSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pConsulterSLayout.createSequentialGroup()
                                .addComponent(tfCommentS, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pConsulterSLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBackS)
                .addGap(65, 65, 65))
        );
        pConsulterSLayout.setVerticalGroup(
            pConsulterSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pConsulterSLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(pConsulterSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbEtat1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pConsulterSLayout.createSequentialGroup()
                        .addGroup(pConsulterSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfNomService1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGroup(pConsulterSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pConsulterSLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jLabel13))
                            .addGroup(pConsulterSLayout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(tfDescription2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pConsulterSLayout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(51, 51, 51)
                        .addGroup(pConsulterSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(cbCat2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfCommentS, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addComponent(jLabel15)))
                .addGap(32, 32, 32)
                .addGroup(pConsulterSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16)
                    .addGroup(pConsulterSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbZone2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCommentS)
                        .addComponent(btnModifierCommentS)
                        .addComponent(btnSupprimerCommentS)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(btnBackS)
                .addGap(48, 48, 48))
        );

        ParentPanel.add(pConsulterS, "card3");

        tpService.addTab("Mes Service", ParentPanel);

        lTitreRechercheS.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lTitreRechercheS.setText("Choisir Une Catégorie : ");

        cbRechercheCat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbRechercheCatMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cbRechercheCatMouseExited(evt);
            }
        });
        cbRechercheCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbRechercheCatActionPerformed(evt);
            }
        });

        tblRechercheS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(tblRechercheS);

        bntRechercheS.setText("Rechercher");
        bntRechercheS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntRechercheSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pRechercheSLayout = new javax.swing.GroupLayout(pRechercheS);
        pRechercheS.setLayout(pRechercheSLayout);
        pRechercheSLayout.setHorizontalGroup(
            pRechercheSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pRechercheSLayout.createSequentialGroup()
                .addGroup(pRechercheSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pRechercheSLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lTitreRechercheS)
                        .addGap(18, 18, 18)
                        .addComponent(cbRechercheCat, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(bntRechercheS))
                    .addGroup(pRechercheSLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pRechercheSLayout.setVerticalGroup(
            pRechercheSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pRechercheSLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pRechercheSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbRechercheCat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lTitreRechercheS)
                    .addComponent(bntRechercheS))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tpService.addTab("Rechercher Un Service", pRechercheS);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tpService, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tpService, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfNomSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomSActionPerformed

    private void tfDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDescriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDescriptionActionPerformed

    private void cbCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCatActionPerformed

    private void cbZoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbZoneActionPerformed

    }//GEN-LAST:event_cbZoneActionPerformed

    private void btnAjoutSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjoutSActionPerformed
        // TODO add your handling code here:
        lerror.setText(" ");

        Service s = new Service();
        Date date = new java.sql.Date(System.currentTimeMillis());
        if (!tfNomS.getText().trim().equals("")) {
            s.setNomService(tfNomS.getText());
            try {
                rsId = zoneDAO.getZoneByName(cbZone.getSelectedItem().toString());
                while (rsId.next()) {
                    s.setZone(rsId.getInt(1));

                }//this.setResizable(false);
            } catch (SQLException ex) {
                Logger.getLogger(FrameAjouterService.class.getName()).log(Level.SEVERE, null, ex);
            }

            s.setDescription(tfDescription.getText());
            s.setType(cbCat.getSelectedItem().toString());
            //s.setZone((int) cbZone.getSelectedItem());
            s.setDateAjout(date);
            s.setEtat("EnCours");
            ServiceDao pdao = new ServiceDao();
            pdao.add(s);
            DefaultTableModel model = (DefaultTableModel) tblService.getModel();
            model.addRow(new Object[]{tfNomS.getText(), tfDescription.getText(), cbCat.getSelectedItem().toString(), s.getDateAjout(), s.getEtat()});
        } else {
            lerror.setText(" Veuiller enter le nom de votre service SVP !");
            tblAllServices.setModel(new ListeService());
            tblMesServices.setModel(new ServiceByUserIdModel());
        }
    }//GEN-LAST:event_btnAjoutSActionPerformed

    private void tpServiceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tpServiceMouseClicked
        // TODO add your handling code here:
        tblAllServices.setModel(new ListeService());

    }//GEN-LAST:event_tpServiceMouseClicked

    private void btnModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierActionPerformed
        // TODO add your handling code here:
        lMsg.setText(" ");

        Service s = new Service();
        Date date = new java.sql.Date(System.currentTimeMillis());
        if (!tfNomService.getText().trim().equals("")) {
            s.setId(Integer.parseInt(labelId.getText()));
            s.setNomService(tfNomService.getText());
            s.setDescription(tfDescription1.getText());
            s.setType(cbCat1.getSelectedItem().toString());
            try {
                rsNom = zoneDAO.getZoneByName(cbZone1.getSelectedItem().toString());
                while (rsNom.next()) {
                    s.setZone(rsNom.getInt(1));
                    System.out.println(rsNom.getInt(1));
                }//this.setResizable(false);
            } catch (SQLException ex) {
                Logger.getLogger(FrameAjouterService.class.getName()).log(Level.SEVERE, null, ex);
            }
            s.setDateAjout(date);
            s.setEtat(cbEtat.getSelectedItem().toString());
            ServiceDao pdao = new ServiceDao();
            pdao.update(s);
            //jScrollPane1.setViewportView(tblService);

        } else {
            lMsg.setText(" Veuiller enter le nom de votre service SVP !");
        }
        tblMesServices.setModel(new ServiceByUserIdModel()); // Act tab apres modif
    }//GEN-LAST:event_btnModifierActionPerformed

    private void bntSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSupprimerActionPerformed
        // TODO add your handling code here:

        FrameAfficherServiceAdmin f = new FrameAfficherServiceAdmin();
        int i = tblMesServices.getSelectedRow();
        Object l = tblMesServices.getValueAt(i, 0);

        ServiceDao pdao = new ServiceDao();

        int j = JOptionPane.showConfirmDialog(null, "la suppression est irréversible. Etes-vous sur de vouloir continuer?", "Veuillez confirmer votre choix", JOptionPane.YES_NO_OPTION);

        if (j == 0) {
            pdao.removeById((int) l);

            tblMesServices.setModel(new ServiceByUserIdModel());

            jScrollPane3.setViewportView(tblMesServices);
        }
    }//GEN-LAST:event_bntSupprimerActionPerformed

    private void tfNomServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomServiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomServiceActionPerformed

    private void btnConsulterSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsulterSActionPerformed
        // TODO add your handling code here:
        int i = tblMesServices.getSelectedRow();
        Object l = tblMesServices.getValueAt(i, 0);
        service_id = (int) l;
        System.out.println(service_id);
        TableModel model = tblMesServices.getModel();
        //labelId.setText(model.getValueAt(i, 0).toString());
        tfNomService1.setText(model.getValueAt(i, 1).toString());
        tfDescription2.setText(model.getValueAt(i, 2).toString());

        cbCat2.setSelectedItem(tblMesServices.getValueAt(i, 3));
        cbEtat1.setSelectedItem(tblMesServices.getValueAt(i, 4));
        cbZone2.setSelectedItem(model.getValueAt(i, 5).toString());
        ParentPanel.removeAll();
        ParentPanel.add(pConsulterS);
        tbCommentMesServices.setModel(new CommentSModel());
        tbCommentMesServices.setVisible(true);
        ParentPanel.repaint();
        ParentPanel.revalidate();

//        pConsulterS.setVisible(true);

    }//GEN-LAST:event_btnConsulterSActionPerformed

    private void tblMesServicesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMesServicesMouseClicked
        // TODO add your handling code here:
        int i = tblMesServices.getSelectedRow();
        TableModel model = tblMesServices.getModel();

        //tfId.setText(model.getValueAt(i, 0).toString());
        labelId.setText(model.getValueAt(i, 0).toString());
        tfNomService.setText(model.getValueAt(i, 1).toString());
        tfDescription1.setText(model.getValueAt(i, 2).toString());

        cbCat1.setSelectedItem(tblMesServices.getValueAt(i, 3));
        cbEtat.setSelectedItem(tblMesServices.getValueAt(i, 4));
        cbZone1.setSelectedItem(model.getValueAt(i, 5).toString());

    }//GEN-LAST:event_tblMesServicesMouseClicked

    private void tfNomService1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomService1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomService1ActionPerformed

    private void cbCat2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCat2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCat2ActionPerformed

    private void btnBackSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackSActionPerformed
        // TODO add your handling code here:
        ParentPanel.removeAll();
        ParentPanel.add(pMesServices);
        ParentPanel.repaint();
        ParentPanel.revalidate();
    }//GEN-LAST:event_btnBackSActionPerformed

    private void btnConsulterSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsulterSMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsulterSMouseClicked

    private void cbRechercheCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbRechercheCatActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cbRechercheCatActionPerformed

    private void cbRechercheCatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbRechercheCatMouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_cbRechercheCatMouseExited

    private void cbRechercheCatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbRechercheCatMouseClicked
        // TODO add your handling code here:


    }//GEN-LAST:event_cbRechercheCatMouseClicked

    private void bntRechercheSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntRechercheSActionPerformed
        // TODO add your handling code here:
        categorie = cbRechercheCat.getSelectedItem().toString();
        System.out.println(categorie);
        ServiceDao pdao = new ServiceDao();
        pdao.findAllByCategorie(categorie);
        tblRechercheS.setModel(new ServiceByCategorieModel());
    }//GEN-LAST:event_bntRechercheSActionPerformed

    private void btnConsulterS1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsulterS1MouseClicked

    }//GEN-LAST:event_btnConsulterS1MouseClicked

    private void btnConsulterS1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsulterS1ActionPerformed
        // TODO add your handling code here:
        int i = tblAllServices.getSelectedRow();
        TableModel model = tblAllServices.getModel();
        Object l = tblAllServices.getValueAt(i, 0);
        service_id = (int) l;
        System.out.println("ID de Service" + service_id);
        // TableModel mod = tbCommentService.getModel();
        //labelId.setText(model.getValueAt(i, 0).toString());
        tfNomService3.setText(model.getValueAt(i, 1).toString());
        tfDescription4.setText(model.getValueAt(i, 2).toString());
        cbCat4.setSelectedItem(tblAllServices.getValueAt(i, 3));
        cbEtat3.setSelectedItem(tblAllServices.getValueAt(i, 4));
        cbZone4.setSelectedItem(model.getValueAt(i, 5).toString());
        ParentPanel2.removeAll();
        ParentPanel2.add(pConsulterS2);
        tbCommentService.setModel(new CommentSModel());
        tbCommentService.setVisible(true);
        ParentPanel2.repaint();
        ParentPanel2.revalidate();

    }//GEN-LAST:event_btnConsulterS1ActionPerformed

    private void tfNomService3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomService3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomService3ActionPerformed

    private void cbCat4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCat4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCat4ActionPerformed

    private void btnBackS2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackS2ActionPerformed
        // TODO add your handling code here:
        ParentPanel2.removeAll();
        ParentPanel2.add(pAllServices);
        ParentPanel2.repaint();
        ParentPanel2.revalidate();
    }//GEN-LAST:event_btnBackS2ActionPerformed

    private void tblAllServicesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAllServicesMouseClicked
        int i = tblAllServices.getSelectedRow();
        Object l = tblAllServices.getValueAt(i, 0);
        service_id = (int) l;
        System.out.println("ID" + service_id);

    }//GEN-LAST:event_tblAllServicesMouseClicked

    private void tblServiceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblServiceMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblServiceMouseClicked

    private void btnCommenterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCommenterActionPerformed
        Comment c = new Comment();
        c.setBody(tfComment.getText());
        java.util.Date date = new java.sql.Date(System.currentTimeMillis());
        c.setCreated_at(date);
        System.out.println("testServiceId" + FrameAfficherServiceAll.getService_id());
        c.setService_id(FrameAfficherServiceAll.getService_id());
        System.out.println("testUserId" + FrameAccueil.getUserId());
        c.setUser_id(FrameAccueil.getUserId());
        CommentDao pdao = new CommentDao();
        pdao.addS(c);
        tbCommentService.setModel(new CommentSModel());
        tfComment.setText("");
    }//GEN-LAST:event_btnCommenterActionPerformed

    private void tfCommentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCommentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCommentActionPerformed

    private void btnSupprimerCommentaireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprimerCommentaireActionPerformed
        int ligneSelectionne = tbCommentService.getSelectedRow();
        Object l = tbCommentService.getValueAt(ligneSelectionne, 0);
        System.out.println(l);
        CommentDao comm = new CommentDao();
        int i = JOptionPane.showConfirmDialog(null, "La suppression est irréversible. Êtes-vous sûr de vouloir continuer?",
                "Veuillez confirmer votre choix",
                JOptionPane.YES_NO_OPTION);

        if (i == 0) {
            comm.removeById((int) l);
            tbCommentService.setModel(new CommentSModel());

        }
    }//GEN-LAST:event_btnSupprimerCommentaireActionPerformed

    private void btnModifierCommentaireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierCommentaireActionPerformed
        int ligneSelectionne = tbCommentService.getSelectedRow();
        Object l = tbCommentService.getValueAt(ligneSelectionne, 0);
        Comment c = new Comment();
        String body;
        CommentDao dao = new CommentDao();
        c.setId((int) tbCommentService.getValueAt(ligneSelectionne, 0));
        body = tfComment.getText();
        c.setBody(body);
        System.out.println(c);
        dao.update(c);
        tbCommentService.setModel(new CommentSModel());
    }//GEN-LAST:event_btnModifierCommentaireActionPerformed

    private void tbCommentServiceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbCommentServiceMouseClicked
        int ligneSelectionne = tbCommentService.getSelectedRow();
        Object l = tbCommentService.getValueAt(ligneSelectionne, 0);
        CommentDao dao = new CommentDao();
        Comment c = new Comment();
        c.setId((int) tbCommentService.getValueAt(ligneSelectionne, 0));
        System.out.println((int) tbCommentService.getValueAt(ligneSelectionne, 0));
        tfComment.setText((String) tbCommentService.getValueAt(ligneSelectionne, 1));


    }//GEN-LAST:event_tbCommentServiceMouseClicked

    private void tbCommentMesServicesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbCommentMesServicesMouseClicked
        int ligneSelectionne = tbCommentMesServices.getSelectedRow();
        Object l = tbCommentMesServices.getValueAt(ligneSelectionne, 0);
        CommentDao dao = new CommentDao();
        Comment c = new Comment();
        c.setId((int) tbCommentMesServices.getValueAt(ligneSelectionne, 0));
        System.out.println((int) tbCommentMesServices.getValueAt(ligneSelectionne, 0));
        tfCommentS.setText((String) tbCommentMesServices.getValueAt(ligneSelectionne, 1));
    }//GEN-LAST:event_tbCommentMesServicesMouseClicked

    private void btnModifierCommentSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierCommentSActionPerformed
         int ligneSelectionne = tbCommentMesServices.getSelectedRow();
        Object l = tbCommentMesServices.getValueAt(ligneSelectionne, 0);
        Comment c = new Comment();
        String body;
        CommentDao dao = new CommentDao();
        c.setId((int) tbCommentMesServices.getValueAt(ligneSelectionne, 0));
        body = tfCommentS.getText();
        c.setBody(body);
        System.out.println(c);
        dao.update(c);
        tbCommentMesServices.setModel(new CommentSModel());
    }//GEN-LAST:event_btnModifierCommentSActionPerformed

    private void btnCommentSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCommentSActionPerformed
         Comment c = new Comment();
        c.setBody(tfCommentS.getText());
        java.util.Date date = new java.sql.Date(System.currentTimeMillis());
        c.setCreated_at(date);
        System.out.println("testServiceId" + FrameAfficherServiceAll.getService_id());
        c.setService_id(FrameAfficherServiceAll.getService_id());
        System.out.println("testUserId" + FrameAccueil.getUserId());
        c.setUser_id(FrameAccueil.getUserId());
        CommentDao pdao = new CommentDao();
        pdao.addS(c);
        tbCommentMesServices.setModel(new CommentSModel());
        tfCommentS.setText("");
    }//GEN-LAST:event_btnCommentSActionPerformed

    private void btnSupprimerCommentSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprimerCommentSActionPerformed
         int ligneSelectionne = tbCommentMesServices.getSelectedRow();
        Object l = tbCommentMesServices.getValueAt(ligneSelectionne, 0);
        System.out.println(l);
        CommentDao comm = new CommentDao();
        int i = JOptionPane.showConfirmDialog(null, "La suppression est irréversible. Êtes-vous sûr de vouloir continuer?",
                "Veuillez confirmer votre choix",
                JOptionPane.YES_NO_OPTION);

        if (i == 0) {
            comm.removeById((int) l);
            tbCommentMesServices.setModel(new CommentSModel());

        }
    }//GEN-LAST:event_btnSupprimerCommentSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension screenSize = tk.getScreenSize();
        int screenHeight = screenSize.height;
        int screenWidth = screenSize.width;
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameAfficherServiceAll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameAfficherServiceAll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameAfficherServiceAll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameAfficherServiceAll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrameAfficherServiceAll fa = new FrameAfficherServiceAll();
                fa.setVisible(true);
                fa.setResizable(false);
                fa.setSize(screenWidth / 2, screenHeight / 2);
                fa.setLocation(screenWidth / 4, screenHeight / 4);
            }
        });
    }

    private void loadAllVille() {
        try {
            ResultSet res = pdao.getAllVille();

            while (res.next()) {

                cbZone.addItem(res.getString(1));
                cbZone1.addItem(res.getString(1));
                cbZone2.addItem(res.getString(1));
                cbZone4.addItem(res.getString(1));

                // System.out.println(res.getString(1));
            }
        } catch (SQLException ex) {
            Logger.getLogger(FrameAjouterService.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadAllCategorie() {
        try {
            ResultSet res = pdao.getCategorie();

            while (res.next()) {

                cbCat.addItem(res.getString(1));
                cbCat1.addItem(res.getString(1));
                cbCat2.addItem(res.getString(1));
                cbCat4.addItem(res.getString(1));
                cbRechercheCat.addItem(res.getString(1));
                // System.out.println(res.getString(1));

            }
        } catch (SQLException ex) {
            Logger.getLogger(FrameAjouterProduit.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ParentPanel;
    private javax.swing.JPanel ParentPanel2;
    private javax.swing.JButton bntRechercheS;
    private javax.swing.JButton bntSupprimer;
    private javax.swing.JButton btnAjoutS;
    private javax.swing.JButton btnBackS;
    private javax.swing.JButton btnBackS2;
    private javax.swing.JButton btnCommentS;
    private javax.swing.JButton btnCommenter;
    private javax.swing.JButton btnConsulterS;
    private javax.swing.JButton btnConsulterS1;
    private javax.swing.JButton btnModifier;
    private javax.swing.JButton btnModifierCommentS;
    private javax.swing.JButton btnModifierCommentaire;
    private javax.swing.JButton btnSupprimerCommentS;
    private javax.swing.JButton btnSupprimerCommentaire;
    private javax.swing.JComboBox cbCat;
    private javax.swing.JComboBox cbCat1;
    private javax.swing.JComboBox cbCat2;
    private javax.swing.JComboBox cbCat4;
    private javax.swing.JComboBox cbEtat;
    private javax.swing.JComboBox cbEtat1;
    private javax.swing.JComboBox cbEtat3;
    private javax.swing.JComboBox cbRechercheCat;
    private javax.swing.JComboBox cbZone;
    private javax.swing.JComboBox cbZone1;
    private javax.swing.JComboBox cbZone2;
    private javax.swing.JComboBox cbZone4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel lMsg;
    private javax.swing.JLabel lTitreRechercheS;
    private javax.swing.JLabel labelId;
    private javax.swing.JLabel lerror;
    private javax.swing.JPanel pAjoutS;
    private javax.swing.JPanel pAllServices;
    private javax.swing.JPanel pConsulterS;
    private javax.swing.JPanel pConsulterS2;
    private javax.swing.JPanel pMesServices;
    private javax.swing.JPanel pRechercheS;
    private javax.swing.JTable tbCommentMesServices;
    private javax.swing.JTable tbCommentService;
    private javax.swing.JTable tblAllServices;
    private javax.swing.JTable tblMesServices;
    private javax.swing.JTable tblRechercheS;
    private javax.swing.JTable tblService;
    private javax.swing.JTextField tfComment;
    private javax.swing.JTextField tfCommentS;
    private javax.swing.JTextField tfDescription;
    private javax.swing.JTextField tfDescription1;
    private javax.swing.JTextField tfDescription2;
    private javax.swing.JTextField tfDescription4;
    private javax.swing.JTextField tfNomS;
    private javax.swing.JTextField tfNomService;
    private javax.swing.JTextField tfNomService1;
    private javax.swing.JTextField tfNomService3;
    private javax.swing.JTabbedPane tpService;
    // End of variables declaration//GEN-END:variables
}
