package GUI;

import dao.UserDao;
import entite.User;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.IOError;
import java.io.IOException;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import utils.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author maroo
 */
public class FrameInscription extends javax.swing.JFrame {

    /**
     * Creates new form FrameInscription
     */
    String im;
   
    
    

    public FrameInscription() {
        
        initComponents();
        btnmodif.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        tfusername = new javax.swing.JTextField();
        tfemail = new javax.swing.JTextField();
        tflastname = new javax.swing.JTextField();
        tffirstname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cboxgender = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        tfphone = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tfmdp1 = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();
        tfmdp2 = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        taadress = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        cbtype = new javax.swing.JComboBox();
        btnadd = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lprofile = new javax.swing.JLabel();
        tfimage = new javax.swing.JTextField();
        btnpar = new javax.swing.JButton();
        lerror = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnmodif = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tfusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfusernameActionPerformed(evt);
            }
        });

        jLabel4.setText("Nom d'utilisateur* :");

        jLabel5.setText("Email* :");

        jLabel6.setText("Mot de Passe* :");

        jLabel7.setText("Genre :");

        jLabel8.setText("Prenom :");

        cboxgender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Homme", "Femme" }));
        cboxgender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxgenderActionPerformed(evt);
            }
        });

        jLabel9.setText("Nom :");

        jLabel10.setText("N° Tel");

        jLabel11.setText("Adresse :");

        tfmdp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfmdp1ActionPerformed(evt);
            }
        });

        jLabel12.setText("Re Mot de Passe");

        taadress.setColumns(20);
        taadress.setRows(5);
        jScrollPane1.setViewportView(taadress);

        jLabel13.setText("Type de compte");

        cbtype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Simple Utilisateur", "Fournisseur" }));

        btnadd.setText("S'inscrire");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        jButton3.setText("Annuler");

        btnpar.setText("Parcourir");
        btnpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(tfimage, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnpar)
                        .addGap(63, 63, 63))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lprofile, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lprofile, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(tfimage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnpar))
        );

        lerror.setForeground(new java.awt.Color(255, 0, 0));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel2.setText("* champ obligatoire ");

        btnmodif.setText("Modifier");
        btnmodif.setToolTipText("");
        btnmodif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodifActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lerror)
                            .addComponent(jLabel13))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnmodif)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnadd)
                                .addGap(7, 7, 7)
                                .addComponent(jButton3))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(cbtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel12)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tffirstname)
                                    .addComponent(tfphone, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tfemail, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tfmdp2)
                                    .addComponent(cboxgender, 0, 120, Short.MAX_VALUE)
                                    .addComponent(tfmdp1)
                                    .addComponent(tfusername, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tflastname))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tfmdp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(tfmdp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboxgender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tflastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(88, 88, 88)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tffirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tfphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbtype))
                .addGap(0, 3, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnadd)
                            .addComponent(jButton3)
                            .addComponent(btnmodif)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lerror)
                        .addGap(21, 21, 21))))
        );

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel14.setText("Inscription");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnparActionPerformed
        JFileChooser chooser = new JFileChooser();

        FileNameExtensionFilter filter = new FileNameExtensionFilter(
            "JPG & GIF Images", "jpg", "gif");
        chooser.setFileFilter(filter);
        int returnVal = chooser.showOpenDialog(btnpar);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            String s = chooser.getSelectedFile().getAbsolutePath();
            Image image = new ImageIcon(s).getImage();
            Image resizedImage = image.getScaledInstance(200, 200, Image.SCALE_DEFAULT);
            lprofile.setIcon(new ImageIcon(resizedImage));
            lprofile.setIcon(new ImageIcon(resizedImage));

            tfimage.setText(chooser.getSelectedFile().getAbsolutePath());
            im = chooser.getSelectedFile().getName();
        }
    }//GEN-LAST:event_btnparActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        UserDao udao = new UserDao();
        String un = tfusername.getText();
        User u1 = udao.findByUserNameI(un);
        System.out.println(u1.getUsername());
        if (u1.getUsername()==null) {
            User u = new User();
            PostFile pf = new PostFile();
            u.setUsername(un);
            u.setUsernameCanonical(tfusername.getText());
            String mail = tfemail.getText();
            EmailValidator emailValidator = new EmailValidator();
            if(emailValidator.validate(mail.trim())) {
                System.out.print("email ok");

                User u2 = udao.findByEmail(mail);
                System.out.println(u2.getEmail());
                if (u2.getEmail()==null) {
                    u.setEmail(mail);
                    u.setEmailCanonical(mail);
                    if(tfmdp1.getText().length()>=6){
                        if (tfmdp1.getText().equals(tfmdp2.getText()) ) {
                            u.setPassword(tfmdp1.getText());
                            u.setEnabled(0);
                            if (cboxgender.getSelectedIndex() == 0) {
                                u.setGender("m");
                            } else {
                                u.setGender("f");
                            }
                            try {

                                u.setPhone(tfphone.getText());
                            } catch (NumberFormatException ex) {
                                lerror.setText("num de tel existe");
                            }
                            u.setLastname(tflastname.getText());
                            u.setFirstname(tffirstname.getText());
                            u.setAdress(taadress.getText());

                            if (cbtype.getSelectedIndex() == 0) {
                                u.setRoles("ROLE_USER");
                            } else {
                                u.setRoles("ROLE_FOURN");
                            }
                            java.sql.Date d = java.sql.Date.valueOf(LocalDate.now());
                            u.setCreated_at(d);
                            u.setImage("http://localhost/Tec/web/uploads/media/profile/" + im);

                            String sp = tfimage.getText();
                            try {
                                pf.upload(sp);
                                lerror.setText("Image telechargé avec succés");

                                // TODO add your handling code here:
                            } catch (Exception ex) {
                                Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);

                            }
                            udao.add(u);
                            JOptionPane.showMessageDialog(null, "Vous êtes Inscrit ! Maintenant Vous êtes appelé a attendre l'activation de votre compte   ");
                        } else {

                            JOptionPane.showMessageDialog(null, "Verifier Mot de passe !");
                        }
                    } else {

                        JOptionPane.showMessageDialog(null, " Mot de passe trés faible !");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Cet email est deja utilisé !, Voulez vous utiliser un autre ");
                }

            } else {
                JOptionPane.showMessageDialog(null, "email Invalid ");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Ce Nom d'utilisateur existe déja !, Voulez vous choisire un autre ");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnaddActionPerformed

    private void tfmdp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfmdp1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfmdp1ActionPerformed

    private void cboxgenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxgenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxgenderActionPerformed

    private void tfusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfusernameActionPerformed

    private void btnmodifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodifActionPerformed
              UserDao udao = new UserDao();
        
        
            User u = new User();
            PostFile pf = new PostFile();
            u.setId(FrameAccueil.getUserId());
            System.out.println(FrameAccueil.getUserId());
            u.setUsername(tfusername.getText());
            u.setUsernameCanonical(tfusername.getText());
            String mail = tfemail.getText();
            EmailValidator emailValidator = new EmailValidator();
            if(emailValidator.validate(mail.trim())) {
                System.out.print("email ok");

               
                    u.setEmail(mail);
                    u.setEmailCanonical(mail);
                    if(tfmdp1.getText().length()>=6){
                        if (tfmdp1.getText().equals(tfmdp2.getText()) ) {
                            u.setPassword(tfmdp1.getText());
                            
                            if (cboxgender.getSelectedIndex() == 0) {
                                u.setGender("m");
                            } else {
                                u.setGender("f");
                            }
                            try {

                                u.setPhone(tfphone.getText());
                            } catch (NumberFormatException ex) {
                                lerror.setText("num de tel existe");
                            }
                            u.setLastname(tflastname.getText());
                            u.setFirstname(tffirstname.getText());
                            u.setAdress(taadress.getText());

                            if (cbtype.getSelectedIndex() == 0) {
                                u.setRoles("ROLE_USER");
                            } else {
                                u.setRoles("ROLE_FOURN");
                            }
                            java.sql.Date d = java.sql.Date.valueOf(LocalDate.now());
                            u.setUpdated_at(d);
                       

                           
                            udao.updateme(u);
                            JOptionPane.showMessageDialog(null, "Votre Profile a été mis à jour  ");
                            System.out.println(u);
                        } else {

                            JOptionPane.showMessageDialog(null, "Verifier Mot de passe !");
                        }
                    } else {

                        JOptionPane.showMessageDialog(null, " Mot de passe trés faible !");
                    }
               

            } else {
                JOptionPane.showMessageDialog(null, "email Invalid ");
            }
         // TODO add your handling code here:
    }//GEN-LAST:event_btnmodifActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameInscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameInscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameInscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameInscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameInscription().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnadd;
    public javax.swing.JButton btnmodif;
    private javax.swing.JButton btnpar;
    public javax.swing.JComboBox cboxgender;
    public javax.swing.JComboBox cbtype;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    public javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lerror;
    public javax.swing.JLabel lprofile;
    public javax.swing.JTextArea taadress;
    public javax.swing.JTextField tfemail;
    public javax.swing.JTextField tffirstname;
    public javax.swing.JTextField tfimage;
    public javax.swing.JTextField tflastname;
    public javax.swing.JPasswordField tfmdp1;
    private javax.swing.JPasswordField tfmdp2;
    public javax.swing.JTextField tfphone;
    public javax.swing.JTextField tfusername;
    // End of variables declaration//GEN-END:variables
}
