/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import dao.ServiceDao;
import entite.Service;
import java.sql.Date;

/**
 *
 * @author Super
 */
public class FrameModifierService extends javax.swing.JFrame {

    /**
     * Creates new form FrameModifierService
     */
    public FrameModifierService() {
        initComponents();// initialiser l'interface
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfNomService = new javax.swing.JTextField();
        tfDescription = new javax.swing.JTextField();
        cbCat = new javax.swing.JComboBox();
        cbZone = new javax.swing.JComboBox();
        btnModifierS = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        cbEtat = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 102));
        jLabel1.setText("Modifier Service");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(126, 49, 145, 22);

        jLabel2.setText("Nom du Service : ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(63, 140, 84, 14);

        jLabel3.setText("Description : ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(63, 194, 63, 14);

        jLabel4.setText("Catégorie :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(63, 249, 54, 14);

        jLabel5.setText("Gouvernorat :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(63, 289, 68, 14);

        tfNomService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomServiceActionPerformed(evt);
            }
        });
        getContentPane().add(tfNomService);
        tfNomService.setBounds(236, 137, 71, 20);
        getContentPane().add(tfDescription);
        tfDescription.setBounds(236, 191, 71, 20);

        cbCat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Maison", "jardinage", "annimaux", "" }));
        cbCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCatActionPerformed(evt);
            }
        });
        getContentPane().add(cbCat);
        cbCat.setBounds(236, 249, 71, 14);

        cbZone.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4" }));
        cbZone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbZoneActionPerformed(evt);
            }
        });
        getContentPane().add(cbZone);
        cbZone.setBounds(236, 286, 71, 20);

        btnModifierS.setIcon(new javax.swing.ImageIcon("C:\\Users\\Super\\Downloads\\1285845671_configuration_edit.png")); // NOI18N
        btnModifierS.setText("Modifier");
        btnModifierS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierSActionPerformed(evt);
            }
        });
        getContentPane().add(btnModifierS);
        btnModifierS.setBounds(131, 362, 123, 57);

        jLabel6.setText("Etat :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(63, 327, 27, 14);

        cbEtat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "enCour", "Réalisé" }));
        getContentPane().add(cbEtat);
        cbEtat.setBounds(236, 324, 71, 20);

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 376, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 454, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 376, 454);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModifierSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierSActionPerformed
        // TODO add your handling code here:
            Service s = new Service();
          Date date = new java.sql.Date(System.currentTimeMillis());
        s.setNomService(tfNomService.getText());
        s.setDescription(tfDescription.getText());
        s.setType(cbCat.getSelectedItem().toString());
        s.setType(cbZone.getSelectedItem().toString());
        s.setType(cbEtat.getSelectedItem().toString());
      s.setDateAjout(date);
      
        ServiceDao pdao = new ServiceDao();
        pdao.update(s);
    }//GEN-LAST:event_btnModifierSActionPerformed

    private void cbCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCatActionPerformed

    private void tfNomServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomServiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomServiceActionPerformed

    private void cbZoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbZoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbZoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameModifierService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameModifierService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameModifierService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameModifierService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameModifierService().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModifierS;
    private javax.swing.JComboBox cbCat;
    private javax.swing.JComboBox cbEtat;
    private javax.swing.JComboBox cbZone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tfDescription;
    private javax.swing.JTextField tfNomService;
    // End of variables declaration//GEN-END:variables
}
